tornadoweb/tornado

tornado/tcpserver.py
=> Fixed TCPServer not setting the correct read_chunk_size.

tornado/gen.py, tornado/test/gen_test.py
This is in reference to the discussion on the mailing list here:
https://groups.google.com/forum/#!topic/python-tornado/pl6UkCnmoIs
A solid consensus hasn't been reached on that discussion yet, but I thought we'd gotten to the point where it would be meaningful to begin discussing working code, which is the purpose of this PR.
=> [feature] Any Future

tornado/websocket.py
Added support for custom web socket protocols.
To add custom protocol implementation user should override get_websocket_protocol_subclass() method in WebSocketHandler subclass.
=> Added support for custom web socket protocols.

docs/coroutine.rst, docs/locks.rst, tornado/locks.py, tornado/test/condition_test.py, tornado/test/runtests.py
Copied from Toro with small improvements.
Squashed version of https://github.com/tornadoweb/tornado/pull/1331
=> Add tornado.locks.Condition.

tornado/simple_httpclient.py
=> Fix simple typo in httpclient exception message

tornado/locks.py, tornado/test/locks_test.py
Two places that Toro's style snuck into Tornado.
=> Event cleanups.

tornado/locale.py, tornado/web.py
To my mind it will be useful to have pgettext function in templates by default.
=> Add pgettext to default template namespace

tornado/locks.py
=> Add docstring to BoundedSemaphore.release.

tornado/locks.py, tornado/test/locks_test.py
Consistent with asyncio's Condition and Event.
=> Define Condition's and Event's repr, not str.

tornado/web.py
=> Prevent bad calls to get_arguments with a presumed default value

tornado/platform/auto.py
Just switched the order of the if statements
=> Fix for running tornado in app engine under Windows

demos/blog/blog.py
=> use key-word "super" replace hard code

docs/locks.rst
100ms sleep doesn't always order the test output on Travis slaves.
=> reliable-queues-doctest

docs/locks.rst, tornado/locks.py
For consistency with queues doctests.
=> Move doctests from locks.rst to locks.py.

demos/webspider/webspider.py, docs/guide.rst, docs/guide/queues.rst
Add a web spider example to demonstrate Queue.
=> Add a web spider example to demonstrate Queue.

docs/releases/next.rst
More detail about porting from toro.Event.
=> More detail about porting from toro.Event.

demos/webspider/webspider.py
Update webspider demo support Python 3
=> Update webspider demo support Python 3

demos/webspider/webspider.py
'urldefrag' is a more clear and convenient way than our won realization.
=> Change the implement of remove_fragment method

docs/gen.rst, docs/guide/coroutines.rst, tornado/gen.py, tornado/http1connection.py, tornado/ioloop.py, tornado/platform/asyncio.py, tornado/simple_httpclient.py, tornado/test/asyncio_test.py, tornado/test/gen_test.py, tornado/test/ioloop_test.py, tornado/test/simple_httpclient_test.py, tornado/test/web_test.py, tornado/web.py
Ensure that native coroutines are accepted everywhere that `Futures` are now.
See #1493
=> More polish for native coroutines

demos/websocket/chatdemo.py
`super()` is the recommended style.
=> Use super() to call super "__init__()"

setup.py
Fedora now uses `dnf`.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/tornadoweb/tornado/1621)
=> Update hints for popular operating systems.

tornado/web.py
The example has unexpected indent. fix #1656
=> fix tornado/web.py #L1075 current_user docstring example

tornado/web.py
=> Added missing % to format a string.

demos/webspider/webspider.py
In order to unify style, add shebang for webspider.py.
=> Add shebang for webspider.py

tornado/platform/windows.py, tornado/process.py, tornado/test/runtests.py, tornado/test/windows_test.py
Document Subprocess as posix-only.
=> Fix error raised in set_close_exec on windows

tornado/process.py
It seems that one more line here is better for read when I lean code from tornado.
=> better format for process.py

tornado/ioloop.py
=> line too long

tornado/curl_httpclient.py
=> curl_httpclient: Set curl PROTOCOLS and REDIR_PROTOCOLS to HTTP|HTTPS

tornado/util.py
python2 version of exec_in could be rewritten to be compatible with python3
more details in http://stackoverflow.com/a/29876520
=> simplify tornado.util.exec_in

.travis.yml, tornado/test/options_test.py
=> options_test: Absolutize `__file__`

tornado/web.py
The previous address has lost.
=> Change the address of Morsel description

demos/websocket/static/chat.js, demos/websocket/templates/index.html
update demo/websocket for https://github.com/tornadoweb/tornado/issues/1790
=> update demo/websocket for updating JQuery to 3.1.0

demos/chat/static/chat.js, demos/chat/templates/index.html
=> Chat demo update

tornado/httpclient.py
httpclient: Document the defaults.
Fixes #1833.
=> httpclient: Document the defaults.

tornado/test/web_test.py, tornado/web.py
This feature is badly documented and lacks unit tests.
=> add unit tests for an application with default_host

tornado/httpserver.py
Extracted from https://github.com/tornadoweb/tornado/pull/1806
=> refactor httpserver request adapters

demos/file_upload/file_receiver.py, demos/file_upload/file_uploader.py, docs/guide/structure.rst, docs/httpclient.rst, tornado/web.py
=> docs: Demonstrate uploading and receiving files

tornado/platform/common.py
=> Use errno_from_exception on error caught in Waker

tornado/iostream.py, tornado/tcpclient.py, tornado/test/tcpclient_test.py
Hello,
I'm opening this PoC to start discussing about a potential solution for #1931.
Please let me know what you think!
Thanks,
Mircea
=> TCPClient: connect using specific source IP address and port

tornado/simple_httpclient.py
=> add support for HTTP 308 redirects

tornado/test/websocket_test.py, tornado/websocket.py
websocket: WebSocketHandler.on_message allows coroutines
Fixes #1650
=> websocket: WebSocketHandler.on_message allows coroutines

tornado/gen.py
This fixes `asyncio.sleep(0)`.
=> gen: handle None in convert_yielded

tornado/test/gen_test.py
=> gen: Add tests for `yield None`

tornado/iostream.py, tornado/test/iostream_test.py
The current behaviour is error-prone and makes it difficult to use the
Future-returning variant of IOStream.write().  This change makes sure
the returned Future is triggered as soon as the corresponding write
is issued.
Replaces #1888
=> Fix IOStream.write() to never orphan Future

tornado/test/process_test.py
This test occasionally fails on pypy on travis-ci.
=> process_test: Report more details when test_sigchild_signal fails

tornado/test/tcpclient_test.py
It appears that on windows the client connect call can sometimes
succeed before the server has processed the request, so introduce
additional synchronization.
=> tcpclient_test: Attempt to deflake on windows

tornado/test/web_test.py, tornado/web.py
=> add missing response codes for python 2.7-3.4

tornado/ioloop.py
=> ioloop: Document the incompatibility of IOLoop and fork()

tornado/test/windows_test.py
=> don't check error code in test_set_close_exec

tornado/test/websocket_test.py, tornado/websocket.py
Swallowing the exception violated the method's interface (by returning
None instead of a Future), and differs from stream-closed behavior in
other contexts in Tornado.
Fixes #1980
=> websocket: Don't swallow exceptions in _write_frame

tornado/options.py, tornado/test/options_test.py, tornado/test/util.py
=> options: Report redefinition errors when underscores are used

appveyor.yml
=> build: Don't double-test on appveyor

tornado/iostream.py
close(exc_info=True) calls sys.exc_info() to get the "current" exception. Unfortunately, on Python 2 this is the last raised exception even if it was caught and silenced (by contrast with Python 3, which has lexically nested exceptions).  This could set ``IOStream.error`` and therefore ``TCPClient.connect``'s raised exception to the wrong error.
Fix by passing the explicit error instance instead.
The context in which I got caught by this was this particular snippet in `SSLIOStream._do_handshake()`:
```
except ssl.SSLError as err:
[...]
elif err.args[0] == ssl.SSL_ERROR_SSL:
try:
peer = self.socket.getpeername()
except Exception:
peer = '(not connected)'
gen_log.warning("SSL Error on %s %s: %s",
self.socket.fileno(), peer, err)
return self.close(exc_info=True)
```
If `socket.getpeername()` …
=> Avoid IOStream.close(exc_info=True)

tornado/queues.py
Hi!
I spent couple hours in debugging to understand what timeout parameter is. So i created this pull request with docs additions to save time of other people.
Thanks.
=> Added information about timeout arg in Queue get and put methods

docs/gen.rst, docs/releases/v4.2.0.rst, tornado/gen.py, tornado/ioloop.py, tornado/locks.py, tornado/queues.py, tornado/test/import_test.py, tornado/util.py
=> ioloop,gen: Unify TimeoutErrors

docs/releases/v3.0.0.rst, docs/releases/v3.0.1.rst, docs/testing.rst, maint/test/redbot/red_test.py, tornado/test/concurrent_test.py, tornado/test/httpserver_test.py, tornado/test/runtests.py, tornado/testing.py
- Remove deprecated LogTrapTestCase
- Make test log detection sensitive to info logs
=> Clean up test logging

tornado/testing.py
=> testing: Fix incorrect docs for gen_test

tornado/http1connection.py, tornado/web.py
=> Do not send/expect Content-Length on 1xx

docs/releases.rst, docs/releases/v4.5.2.rst, setup.py, tornado/__init__.py, tornado/netutil.py, tornado/platform/common.py, tornado/tcpclient.py
=> Cherrypick FD_CLOEXEC change for 4.5.2

tornado/iostream.py
=> fix: iostream exception alias

tornado/iostream.py
See #2008 for reasons why this might be necessary.
=> Don't keep any reference to memoryviews

.travis.yml
This may fix weird test failures as seen in #2193
=> travis.yml: Upgrade pypy3

tornado/netutil.py, tornado/test/netutil_test.py
see https://github.com/tornadoweb/tornado/issues/2196 for details
=> Add family argument to OverrideResolver->resolve method

tornado/options.py
=> Document that options can be booleans

.travis.yml, docs/releases.rst, docs/releases/v4.5.3.rst, setup.py, tornado/__init__.py, tornado/curl_httpclient.py, tornado/http1connection.py, tornado/iostream.py, tornado/options.py, tornado/test/httpserver_test.py, tornado/test/iostream_test.py, tornado/test/options_test.py, tornado/test/simple_httpclient_test.py, tornado/test/util.py, tornado/test/web_test.py, tornado/test/websocket_test.py, tornado/testing.py, tornado/web.py, tornado/websocket.py
=> Release 4.5.3

.flake8, .travis.yml, demos/benchmark/template_benchmark.py, maint/test/appengine/common/runtests.py, tornado/locks.py, tornado/test/gen_test.py, tornado/websocket.py, tox.ini
@ploxiln Thanks for getting us ready for this, now let's lock this in to prevent regressions.
=> build: Enforce flake8-cleanliness in CI

tornado/iostream.py, tornado/test/iostream_test.py
This PR is an alternative to #2193, with a goal of minimizing duplication between the `read_into` and regular paths. To do this, it first changes the regular code paths to be based on the `socket.recv_into` interface (with memory allocation behavior that matches what happened before), then implements `IOStream.read_into` by swapping out the buffers used. 
cc @pitrou
=> iostream: Add read_into

docs/guide/security.rst, tornado/web.py
=> docs: Add warnings about DNS rebinding attacks

tornado/websocket.py
=> Only invoke select_subprotocol() when the client requests it

docs/guide/async.rst
Add missing import for AsyncHTTPClient for Future example
=> Add missing import for AsyncHTTPClient

docs/releases.rst, docs/releases/v5.0.2.rst, setup.py, tornado/__init__.py, tornado/httpclient.py, tornado/ioloop.py, tornado/platform/asyncio.py, tornado/test/asyncio_test.py, tornado/test/ioloop_test.py, tornado/test/testing_test.py, tornado/testing.py
=> release 5.0.2

docs/releases/v5.0.0.rst
It removes repeated lines in
docs for release 5.0.0
=> docs: Remove repeated lines.

.travis.yml, demos/blog/blog.py, tornado/locks.py, tornado/web.py, tornado/websocket.py
This was being run from the wrong directory in CI so some errors had
slipped in.
=> Fix lint checks

tornado/test/web_test.py, tornado/web.py
=> web: finish() and render() now return Futures

tornado/autoreload.py, tornado/test/autoreload_test.py
=> autoreload: Preserve wrapper with internal reload

tornado/platform/asyncio.py, tornado/test/ioloop_test.py, tornado/test/simple_httpclient_test.py
Also fix another test that has been flaky recently.
=> asyncio: Fix a race between close and initialize

demos/s3server/s3server.py
The s3server demo has many bugs runnning under Python2.7+ or python3+!
=> demo: update s3server to newest python

demos/chat/static/chat.js, tornado/test/import_test.py, tornado/wsgi.py
Additional minor changes to tests and demos.
=> wsgi: Avoid touching the asyncio event loop at import time

tornado/websocket.py
This eliminates the possibility of messages (especially pings) being
sent in the middle of the closing process (which is generally harmless
but results in errors being logged).
Fixes #2447
=> websocket: Improve detection of closing websocket connections

tornado/test/autoreload_test.py
This sometimes fails with a "file in use" error while cleaning up the
temp directory. Add a sleep and retry in case we've reached our
teardown before the child process has released its locks.
=> test: Deflake autoreload_test on windows

docs/guide/coroutines.rst
=> Fix run_in_executor call in user guide

demos/blog/blog.py, docs/guide/coroutines.rst, docs/releases.rst, docs/releases/v5.1.1.rst, setup.cfg, setup.py, tornado/__init__.py, tornado/http1connection.py, tornado/ioloop.py, tornado/test/web_test.py
Mostly doc updates; the only non-doc changes are from #2449. 
Updates #2451
=> branch5.1: Backport various changes

tornado/test/auth_test.py
The bugs fixed in #2496 were already fixed in the 6.0 branch, but the
tests added there are still useful
=> auth: Forward-port tests from branch5.1

demos/s3server/s3server.py, tornado/locale.py
Hello,
This is a patch to prevent resource leaks and uniformizing the use of the `with` context manager.
=> Fix ResourceWarning: unclosed file

.flake8, tornado/test/web_test.py, tornado/util.py, tornado/web.py
due to flake8 / pyflakes / pycodestyle updates
assuming there is a good chance of continuing maintenance of the tornado 5.1 branch
=> new flake8 warning fixes for 5.1 branch

docs/guide/running.rst, docs/index.rst, docs/releases.rst, docs/releases/v6.0.1.rst, docs/releases/v6.0.2.rst, tornado/platform/twisted.py, tornado/process.py, tornado/tcpserver.py
Forward-port 6.0.x release notes, add notes about things not available on windows.
=> Misc docs updates

tornado/web.py
Feature enhancement in response to #2625.
=> Allow RequestHandler.get to accept **kwargs.

tornado/log.py
=> Added color for logging.CRITICAL = 5 (Magenta).

tornado/iostream.py
This fixes #2651. See the issue for discussion. 
Pinging @bdarnell for review.
=> check that stream is open before trying to read

docs/releases.rst, docs/releases/v6.0.3.rst
Merging release notes to master
=> Release notes for 6.0.3

tornado/httputil.py
=> httputil: A couple of small performance improvements

tornado/http1connection.py, tornado/web.py
Less code and seems easier to read.
=> Simplify chained comparisons.

README.rst
This pull request is related to #2747 and might be invalidated by a redirect.
=> Use HTTPS link for tornado website.

tornado/routing.py, tornado/test/web_test.py
Fixes #2744
~~I will add tests tomorrow.~~ done
=> Fix unescaping of regex routes

demos/webspider/webspider.py
Added an extra set for handling dead links, and reporting.
One consequence of this is that using this script will "work" offline, but will report that some all the links were not fetched.
Addresses Issue #2764
=> Dead link handling

tornado/process.py
=> process: correct docs of fork_processes exit behavior

demos/blog/blog.py
Closes #1824 
I think it was missing only a PR to apply @joshsziegler 's suggestion?
Cheers
Bruno
=> Use bcrypt's checkpw instead of == in demo blog app

tornado/iostream.py
Update comment from #2690 about ssl module exceptions.
=> iostream: Update comment

docs/releases/v2.2.0.rst, tornado/http1connection.py, tornado/httpserver.py, tornado/httputil.py, tornado/options.py, tornado/platform/asyncio.py, tornado/test/ioloop_test.py, tox.ini
I fixed some typos that I found within the code, comments, docstrings and docs.
Let me know if you want to change something. :slightly_smiling_face:
=> Fix some typos

tornado/websocket.py
=> Stop ping_callback if websocket client special ping_interval

.travis.yml, tox.ini
- Added arm64 jobs in travis.yml
- Added Cibuildwheel to build wheels for ARM64 and x86 platforms.
=> Added arm64 jobs for Travis-CI

.travis.yml
let's see if an updated pypy will work
=> test: update Travis-CI matrix pypy version

tornado/auth.py
Hi,
i've updated how to register application with Google OAuth2 documentation
CMIIW.
=> Update how to register application with Google 

tornado/wsgi.py
=> wsgi: Update docstring example for python 3

tornado/websocket.py
#2982
My first ever pull request ^^
=> Dict support for WebSocketClientConnection.write_message method

tornado/http1connection.py
=> Allowed set max_body_size to 0

.github/workflows/test.yml, tornado/options.py, tox.ini
=> build: Add python 3.11 alphas to CI

tornado/platform/asyncio.py
same catch as in `add_callback` for the same reasons - the selector thread may race with an `asyncio_loop.close` call in the main thread
seen running tests with pytest-asyncio
=> swallow "Event loop is closed" from selector thread

docs/guide/security.rst
=> docs: Delete a redundant sentence

.github/workflows/build.yml, .github/workflows/test.yml
https://github.com/actions/checkout
https://github.com/actions/setup-python
=> Upgrade actions/checkout and actions/setup-python

tornado/platform/asyncio.py
See https://twitter.com/raymondh/status/1252759650224619521
=> avoid thread unsafe iteration of _ioloop_for_asyncio

tornado/tcpserver.py, tornado/test/tcpserver_test.py, tornado/web.py
In particular, this makes it easier to use reuse_port.
=> tcpserver,web: Pass more arguments through listen.

docs/releases/v6.2.0.rst, tornado/__init__.py
=> Set version number to 6.2.0

tornado/iostream.py
Since PR #3087, this attribute is always zero (except for temporary
usage in _consume) and can be removed.
=> iostream: Remove _read_buffer_pos attribute

SECURITY.md
=> Create security policy document

.readthedocs.yaml
This moves away from web-based settings and permits per-release
changes.
=> docs: Add config file for readthedocs

tornado/test/wsgi_test.py, tornado/wsgi.py
Builds on #3210, adding test cases and support for streaming responses.
=> wsgi: Support ThreadPoolExecutor

.github/workflows/build.yml
Eliminates some more deprecation warnings
=> ci: Update setup-qemu-action version

tornado/web.py
Hello, this is my first time submitting a PR here.
This PR simply fixes a typo in a docstring.
=> Fix syntax error in docstring

.flake8, demos/blog/blog.py, demos/google_auth/main.py, requirements.txt, tornado/concurrent.py, tornado/gen.py, tornado/simple_httpclient.py, tornado/test/__main__.py, tornado/test/escape_test.py, tornado/test/ioloop_test.py, tornado/websocket.py
=> *: Update black

tornado/test/iostream_test.py
Unclear what the issue is but skip the test for now.
=> test: Skip a closed connection test with curl and macOS

.github/workflows/test.yml
This reverts commit 5eea9534563340904fe010d0f7433d35cedb8dfb.
=> Revert "ci: Temporarily pin 3.14-alpha.4"

tornado/httputil.py
=> httputil: Remove a debug print left in by mistake

docs/web.rst, tornado/test/websocket_test.py, tornado/websocket.py
Master branch counterpart of #3513 on branch6.5
=> websocket_ping: fix ping interval with non-zero timeout

.github/workflows/build.yml, .github/workflows/test.yml, pyproject.toml, tornado/test/web_test.py, tox.ini
=> Build cp314 & cp314t wheels
