tornadoweb/tornado

docs/guide/async.rst

The code example only worked with Python 3 and above, now works with all versions.
Explanation added with the change.

Changed 'return' to 'raise gen.Return()' to fix Issue #1292

---

tornado/httputil.py
tornado/test/httputil_test.py
tornado/wsgi.py

HTTPServerRequest.body should be bytes but it is an empty string that
occurs in Python3 when pass no body to HTTPServerRequest.

Ensure that HTTPServerRequest.body is a byte string

---

tornado/websocket.py

As RFC 6455 recommends for asnwer for unsopported protocol.

Mention in Sec-WebSocket-Version all versions supported by tornado

---

tornado/web.py

Our production logs are currently getting flooded with errors from clients sending bad XSRF tokens, e.g.:
Traceback (most recent call last): 
...
File "/app/.heroku/python/lib/python2.7/site-packages/tornado/web.py", line 1190, in xsrf_form_html 
escape.xhtml_escape(self.xsrf_token) + '"/>' 
File "/app/.heroku/python/lib/python2.7/site-packages/tornado/web.py", line 1070, in xsrf_token 
version, token, timestamp = self._get_raw_xsrf_token() 
File "/app/.heroku/python/lib/python2.7/site-packages/tornado/web.py", line 1104, in _get_raw_xsrf_token 
version, token, timestamp = self._decode_xsrf_token(cookie) 
File "/app/.heroku/python/lib/python2.7/site-packages/tornado/web.py", line 1122, in _decode_xsrf_token 
_, mask, masked_token, timestamp = cookie.split("|") 
ValueError: too many values …

Handle bad xsrf tokens more gracefully

---

tornado/ioloop.py

I think that to know if a PeriodicCallback is running or not is important. For example, not to make duplicate PeriodicCallback.

add is_running to get callback state

---

tornado/websocket.py

It is currently extremely difficult to subclass WebSocketClientConnection without reimplementing websocket_connect due to the fact that WebSocketClientConnection is never really exposed outside the websocket module. In my program, my websocket client is also operating as a HTTP server so needing to loop on the websocket client's read_message is awkward.  I ended up subclassing WebSocketClientConnection and overriding its on_message to act more like an expected callback-type function but it seems like a hack since I also had to reimplement websocket_connect to use my own class.
My idea is to move the call the parent's __init__ to a connect function (which admittedly is also hacky) and change the connect_future's eventual return value to True/False value instead of returning a handle to the …

Merge websocket_connect into the WebSocketClientConnection class

---

tornado/test/web_test.py
tornado/web.py

This makes sure if you pass `httponly=False` or `secure=False` it does not add those flags to the Set-Cookie header.
Fixes #1324

Skip falsy values for some SimpleCookie flags

---

tornado/ioloop.py

* when the system time changes, jumps into the future make the _schedule_next method do a busy wait.
* on slow machines (RPi), jumps of a few months into the future can block the loop for a few minutes
=> added a check for big differences in current system time and the current value of the next scheduled timeout
On a first boot of an older RPi image, tornado sometimes starts before date&time gets updated through NTP, hence blocking the ioloop for several minutes.

Avoid busy waiting in ioloop when system time is skipped forward 

---

tornado/gen.py
tornado/test/gen_test.py

In Python 3 every exception has an auto-attached `__context__` exception if it was
raised while an existing exception was being handled.  This is often a very
useful property and allows users to see the underlying cause of many problems.
More info about `__context__`: https://www.python.org/dev/peps/pep-3134/
However, when dealing with async code via coroutines this feature can suddenly
become a pretty big issue.  Namely, if you generator.throw back into a coroutine
to raise an exception in the correct scope, and that coroutine raises an
exception at a later time you can have nested exceptions which shouldn't
logically be nested.
This patch resolves this issue in the coroutine code by moving the gen.throw
outside of the exception handler.  By doing this the user-code scope is able to …

Coroutine exception __context__ leak in python 3

---

tornado/websocket.py

_on_close_called is always False.

_on_close_called is set to True (was always False)

---

tornado/locale.py

Add double colon for code blocks to be rendered as code. Fix minor typos.

Fix doc typos (pgettext)

---

tornado/locks.py
tornado/test/locks_test.py

Next I'll propose a reimplementation of Semaphore in terms of Condition in order to reuse its logic for cleaning up timed-out waiters.

Fix memory leak in Semaphore.

---

maint/test/redbot/red_test.py
tornado/test/web_test.py
tornado/web.py

Fixed #1218, please review this.
1. Split `If-None-Match` with `,` to handle multiple etag in a single header.
2. If "*" is given and any current entity exists for that resource, this method should return `True`.
3. Find etag match in tags (maybe including weak validator).

Fixed #1218.

---

tornado/test/web_test.py
tornado/web.py

Fixed #1123 by removing `urljoin` because joining request uri with redirect url is doing nothing for now.
Although I agree with using `urljoin` with `full_uri()` as its base is more better way to go, this patch temporarily fixes the issue.

Fixed double slash redirect issue

---

docs/coroutine.rst
docs/queues.rst
tornado/queues.py
tornado/test/queues_test.py
tornado/test/runtests.py

This is consistent with the latest API for asyncio. It raises special QueueFull and QueueEmpty errors instead of the standard Queue.Full and Queue.Empty, and there is no separate JoinableQueue, see [Tulip issue 220](https://code.google.com/p/tulip/issues/detail?id=220).
LifoQueue and PriorityQueue will come next.

Add tornado.queues.

---

tornado/locks.py
tornado/test/locks_test.py

Unfortunately, small differences prevent me from factoring this with _set_timeout in queues.py: Condition.wait wants to set the result to False, rather than throwing TimeoutError, and both timeouts call self._garbage_collect, which is not needed in Queue.

Cancel timeouts in Condition.wait and Semaphore.acquire.

---

tornado/autoreload.py

Changed th system module values check to return a list.
In Python 3 it returns a dict_view which could occassionally produce
a runtime error of "dictionary changed size during iteration".

Fixed autoreload for Python 3

---

tornado/gen.py
tornado/test/gen_test.py

This prevents failures in cases like the following:
f = <some future>
yield [f, f]

Allow the same future multiple times in `multi_future`

---

tornado/simple_httpclient.py
tornado/test/simple_httpclient_test.py
tornado/websocket.py

This change allows the SimpleHTTPClient to receive responses larger then `max_buffer_size`. This should allow downloading of very large files without increasing max_buffer_size to unreasonable values.
Intended usage:
```python
#!/usr/bin/env python
import tornado.gen
import tornado.ioloop
import tornado.httpclient
@tornado.gen.coroutine
def main():
url = 'http://releases.ubuntu.com/14.10/ubuntu-14.10-desktop-amd64.iso'
http = tornado.httpclient.AsyncHTTPClient(max_body_size=1024*1024*1024*5)
with open('/dev/null', 'wb') as f:
response = yield http.fetch(url,
streaming_callback=f.write,
request_timeout=3600)
tornado.ioloop.IOLoop.current().run_sync(main)
```

Add max_body_size parameter to SimpleHTTPClient

---

tornado/concurrent.py
tornado/test/concurrent_test.py

Add arguments to customize attribute names used in `run_on_executor`, so clients can use any attribute name they like.
```python
@run_on_executor(io_loop='_io_loop', executor='_executor')
def do_something(self):
pass
```

Add arguments to run_on_executor

---

tornado/locks.py
tornado/test/locks_test.py

The change to the Condition.wait examples is a bugfix. The change to the argument name for Lock.acquire is a judgment call, neither threading.Lock.acquire nor asyncio.Lock.acquire have any timeout argument at all. I think renaming it "timeout" is consistent within Tornado.

Timeouts not deadlines.

---

tornado/escape.py
tornado/test/escape_test.py

While the existing code handles references like &#32; properly,
it doesn't handle the valid case where the number is specified
in hex. For example 'foo&#32;bar', 'foo&#x20;bar' and 'foo&#X20;bar'
should all decode to 'foo bar'. The changes in escape.py check
for the 'x' and decode appropriately. Also added unit tests for
unescaping strings with numeric references.

Modify xhtml_unescape to handle hex numeric refs

---

MANIFEST.in

When packaging tornado for Gentoo I found the documentation was not
available in the sdist provided on pypi.  This adds the documentation so
that users can choose to install it locally.

add docs recursively to MANIFEST.in

---

tornado/auth.py
tornado/test/auth_test.py

-   Added a Google user info API URL to `GoogleOAuth2Mixin`
-   Added code to get user object to the `GoogleOAuth2Mixin.get_authenticated_user` docstring example
-   Added user object process to the auth tests
-   Changed what looks like the wrong function in `oauth2_request`

Add Google OAuth2 user info request.

---

tornado/httpserver.py

This [line](https://github.com/tornadoweb/tornado/blob/master/tornado/httpserver.py#L191) seems useless.
We handle ```self.protocol``` [here](https://github.com/tornadoweb/tornado/blob/master/tornado/httpserver.py#L206-L211)

Remove an useless line

---

.travis.yml
tornado/gen.py
tornado/locks.py
tornado/queues.py
tornado/test/gen_test.py
tornado/test/locks_test.py
tornado/test/queues_test.py
tornado/test/util.py
tox.ini

`Lock` and `Semaphore` support `async with`. All of the `queues` and `WaitIterator` support `async for`. It is now possible to yield a list of awaitables, not just `Futures`.
@ajdavis

Support Python 3.5 `async` statements

---

tornado/iostream.py
tornado/test/iostream_test.py

When a callback is supplied, the future is not created. Make sure
it is used only if it was initialized, otherwise we lose the
error that was originally raised.

Fix error handling in read_until_close

---

.travis.yml

> Full disclosure I work for Codecov
I've been waiting to make this pull request for some time now :) Codecov's entire product is using Tornado as its http web server. I adore this project and would be proud to have it use Codecov as its coverage product.
Some of our core features include:
- Seamless overlay of coverage reports in Github with our browser extensions. [Video](https://www.youtube.com/watch?v=d6wJKODB8_g)
- Awesome pull request comments. [Example](https://gist.github.com/codecov-io/ba612976215481e7f27c)
- Github commit status integration to ensure coverage meets minimum standards
- Automatic unified builds. See [pyca/cryptography](https://codecov.io/github/pyca/cryptography) for example
- Storing build environment variables.
I look forward to your feedback! You can find the …

use Codecov as coverage provider

---

tornado/log.py
tornado/test/log_test.py

Sometimes we want to log messages into files that separated by times(e.g. by days) rather than by file-size.
For that, define `rotating_mode='timed'` for tornado options

add timed rotating mode for logging into separated files in tornado.log

---

tornado/netutil.py
tornado/test/netutil_test.py
tornado/testing.py

This option is `False` by default, because not all platforms support it. Also there's a workaround for old versions of Python which don't export `SO_REUSEPORT` constant even if it supports by a kernel.
Related to #1513

netutil.bind_sockets: add `reuse_port` option to set SO_REUSEPORT

---

tornado/ioloop.py

Locking the callback_lock is unnecessary when adding callbacks from the ioloop's thread.
As it's been noted in add_callback_from_signal, the ioloop won't need to be woken up in those cases, and in fact the logic excludes calling wake from the ioloop's thread. Without such a need, the operation of adding the callback is atomic. If it interrupts a thread that is also adding a callback it cannot harmfully interfere: either exactly one unnecessary wake will be induced, which is harmless, or the wake won't happen at all, which would be correct since it's already polling.
The lock has a big performance impact on add_callback. With it, profiling shows add_callback taking around 160us per call on average from the main thread. Without the lock, that time drops to about 30us.
To implement this, …

Remove synchronization in add_callback from the ioloop thread

---

tornado/curl_httpclient.py
tornado/test/httpclient_test.py

Hi and thanks for maintaining Tornado!
The Tornado curl client currently chokes on multi-line headers without a colon:
```
Traceback (most recent call last):
File "tornado/curl_httpclient.py", line 468, in _curl_header_callback
headers.parse_line(header_line)
File "tornado/httputil.py", line 190, in parse_line
name, value = line.split(":", 1)
ValueError: need more than 1 value to unpack
```
A sample case (apparently X-XSS-Protection is notorious for multi-line headers):
```
curl --trace /tmp/curl http://www.88gala.com/js/mage/adminhtml/sales.js
[...]
<= Recv header, 22 bytes (0x16)
0000: 58 2d 58 53 53 2d 50 72 6f 74 65 63 74 69 6f 6e X-XSS-Protection
0010: 3a 20 31 3b 20 0a                               : 1; .
<= Recv header, 13 bytes (0xd)
0000: 09 6d 6f 64 65 3d 62 6c 6f 63 6b 0d 0a …
```

Allow multi-line headers in CurlAsyncHTTPClient

---

.travis.yml
tornado/simple_httpclient.py
tornado/test/httpclient_test.py
tornado/test/simple_httpclient_test.py

simple_httpclient: Don't call streaming_callback for redirects.

---

tornado/websocket.py

`_frame_compressed` should not be overwrite in continuation frames. According to the Protocol:
https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-13#section-8.2.3.1
"the RSV1 bit is set only on the first frame"

Fix incorrect inspection of WebSocket RSV1 bit.

---

tornado/auth.py
tornado/test/auth_test.py

Return access tokens as strings instead of bytes on python 3,
making the user objects json-encodable.
Add a basic test for FacebookGraphMixin.
Fixes #1532 
cc @wannabeCitizen

Fix a regression in FacebookGraphMixin in the 4.3 dev series.

---

README.rst
docs/index.rst

Removed links to [facebook.com](https://code.facebook.com/projects/) as Tornado is no longer featured. As discussed in https://github.com/tornadoweb/tornado/pull/1537.

Removed links to facebook.com.

---

tornado/test/testing_test.py
tornado/testing.py

Allows a Python 3.5 native coroutine declared with "async def" to be decorated with @gen_test. Raises exception if a test case includes a native coroutine that is *not* decorated with gen_test.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/tornadoweb/tornado/1550)

Update gen_test for native coroutines.

---

tornado/speedups.c

This fixes the gcc warning:
tornado/speedups.c:49:1: warning: function declaration isn’t a prototype
[-Wstrict-prototypes]
initspeedups() {
^

Add void to empty function parameter

---

.travis.yml
setup.py
tornado/gen.py
tornado/test/asyncio_test.py
tornado/test/twisted_test.py

I anticipate confusion around the differing behavior based on whether or
not these packages are installed, so it's better to just make them
mandatory (except on app engine).

Make singledispatch and backports_abc mandatory dependencies.

---

docs/conf.py

PEP8 fix docs/conf.py:91:1: E122 continuation line missing indentation

---

tornado/test/web_test.py

Always convert `__file__` to an absolute path (this is already
guaranteed in Python 3.4+, but in older versions it would sometimes be
relative). Encode the path so the test can pass when run from a
directory containing spaces or other special characters.
Fixes #1565

Make test_root_static_path more robust.

---

tornado/http1connection.py
tornado/test/simple_httpclient_test.py

If an HTTP response contains both Content-Length and
Transfer-Encoding headers, flag this as an error as
per RFC 7230, Section 3.3.3#3. Also added a unit test
to validate the code.

Check for Content-Length and Transfer-Encoding

---

tornado/web.py

For unittesting I start and stop the server in setUp and tearDown. If I use Application.listen I don't have a reference to the HTTPServer and cannot close the socket. Binding it to the same address the next time will result in a address in use error. If the server is returned, calling close on it will allow the address/port to be reused.

Return HTTPServer in Application.listen

---

tornado/testing.py

Fixes #1573: Grab first localhost socket when more than one localhost interface registered

---

tornado/http1connection.py

Allows use of http.client.HTTPStatus in RequestHandler.set_status
'%s' % http.client.OK == 'HTTPStatus.OK'
'%d' % http.client.OK == '200'

Cast start_line.code to an integer

---

.travis.yml

Instead of running a DEPS=false version of every test, just run one
test environment per version and use a separate virtualenv for basic
tests in the DEPS=false case.

Streamline travis-ci build.

---

.travis.yml
docs/index.rst
tornado/platform/auto.py
tox.ini

The `monotonic` pypi module is better maintained and much more widely used. Let's support it as an alternative to `Monotime`.

Add monotonic as an alternative to Monotime

---

tornado/curl_httpclient.py
tornado/test/curl_httpclient_test.py

If `_curl_setup_request` fails, the failing curl instance would be permanently excluded from free_list,  because `_finish` will never be called. Once this has happens `max_clients` times, no future request will ever complete.
This can be seen by requesting a non-ascii URL `max_clients + 1` times.

CurlAsyncHTTPClient: free_list starvation if setup fails

---

tornado/web.py

I did not realize that RequestHandler.initialize() is called before every single request.
For me, 'subclass initialization' suggests that this function is called only once for each subclass definition.
Seems like I am not the only one, according to [this SO question] (http://stackoverflow.com/questions/15199028/does-initialize-in-tornado-web-requesthandler-get-called-every-time-for-a-reques)

Missing hint in documentation

---

tornado/websocket.py

Calling super method by `Request.__init__(self)` cannot handle MRO properly.

Use super() to call super "__init__()"

---

tornado/httpclient.py

If request is HTTPRequest, then any kwargs in [fetch](https://github.com/tornadoweb/tornado/blob/master/tornado/httpclient.py#L206) won't work. And there is no warning or error happen.
Now we can do something like:
req = httpclient.HTTPRequest(url, method="POST", body=data)
response = httpclient.fetch(req, request_timeout=20)
I think it is a better fetch.

make kwargs always work in AsyncHTTPClient.fetch()

---

tornado/simple_httpclient.py
tornado/test/simple_httpclient_test.py

They all raise "HTTP 599: Timeout", it would be more convenient to debug timeout problem with more detailed information. In this pull request, different timeout type will have different error message. Those messages are:
1. "HTTP 599: Timeout in request queue"
2. "HTTP 599: Timeout while connecting"
3. "HTTP 599: Timeout during request"

Differentiate HTTPError(599, "Timeout") raised by SimpleAsyncHTTPClient

---

tornado/test/util_test.py
tornado/test/web_test.py
tornado/util.py
tornado/web.py

for #1609.
* implemented `tornado.util.re_unescape`
* use the `re_unescape` in `tornado.web.URLSpec._find_groups` so it would return unescaped urls
* add some test for the above

reverse_url should unescape regex string

---

tornado/test/web_test.py

There is a gap in `RaiseWithReasonTest` test case. This PR adds a test method that calls `__str__` function from an instance of `HTTPError` class, without `reason` args. It should use `tornado.httputils` to define this HTTP status description or return "Unknown".

Add a test for HTTPError.__str__ when it uses httputils.

---

tornado/auth.py

Verification with appsecret_proof can be used: See https://developers.facebook.com/docs/graph-api/securing-requests

Verifying Facebook Graph API Calls

---

tornado/httpclient.py

Modify callback function name of the `AsyncHTTPClient` example usage.

Modify an inappropriate comments for tornado.httpclient.AsyncHTTPClient

---

tornado/escape.py
tornado/http1connection.py
tornado/httputil.py
tornado/test/web_test.py
tornado/util.py
tornado/web.py

Values in HTTPHeaders were typed inconsistently: the class itself
assumed that values were of type str, while many callers assumed they
were bytes. Since headers are practically restricted to ascii, this
would work on python 2 but fail when certain combinations were
encountered on python 3 (notably the combination of GzipContentEncoding
with multiple preexisting Vary headers).
This commit adds a test and fixes the bug, and also adds enough type
annotations that mypy was able to report errors in the old incorrect
code.
Fixes #1670

Begin to fix type confusion in HTTPHeaders.

---

tornado/test/web_test.py
tornado/web.py

This is primarily to avoid the following error in `check_xsrf_cookie` when an user sends invalid cookies:
> TypeError: a bytes-like object is required, not 'NoneType
This fixes the error handling of xsrf cookies last changed by https://github.com/tornadoweb/tornado/pull/1299

Avoid uncaught exception when _xsrf argument could not be decoded

---

setup.py

As Python 3.2 support was dropped one can check 2.7.x dependency only.
Tornado running on Python 2.7.9+ doesn't need this backported package,
but some Python packages like circus check package dependencies at
runtime and insist on having backports.ssl_match_hostname installed,
though they don't even use this particular feature.
So checking for exact version makes life of package maintainer easier
especially on embedded Linux distributions like Buildroot.

Don't require backports.ssl_match_hostname on Python 2.7.9 and newer

---

tornado/http1connection.py
tornado/test/httpserver_test.py

This fixes #1718 .
As many HTTP clients allow to override Content-Length value to something which is non-integer, I think closing the connection immediately for this case is far more better than raising `ValueError`.

Fixed #1718

---

tornado/test/netutil_test.py

this fixes the UnboundLocalError issue
"UnboundLocalError: local variable 'sockets' referenced before assignment"
Thanks Ondřej Nový for the help

Fix testsuite failure when sockets is not defined

---

tornado/ioloop.py

One of our services uses a lots of callbacks (~15k per IOLoop) and performs massive network IO. During profiling we'd found that significant amount of time consumed in the _Timeout.__lt__ method. Current implementation constantly builds two tuples per comparison. Proposed one pre-builds tuple
during _Timeout creation. Its about ~40% faster. 
In [1]: from tornado.ioloop import _Timeout, IOLoop
In [2]: io = IOLoop.current()
In [3]: t0 = _Timeout(io.time(), None, io)
In [4]: t1 = _Timeout(io.time(), None, io)
In [5]: %timeit t0 < t1
1000000 loops, best of 3: 587 ns per loop
In [6]: %timeit t0 < t1
1000000 loops, best of 3: 336 ns per loop

_Timeout.__lt__ speedup

---

docs/guide/coroutines.rst
docs/releases/v4.2.0.rst
tox.ini

As per their email ‘Changes to project subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs link for their .org -> .io migration for hosted projects

---

tornado/http1connection.py
tornado/test/simple_httpclient_test.py
tornado/test/web_test.py
tornado/web.py

These changes relate to #1736:
* http1connection now also considers 204 to decide when chunking isn't necessary
* RequestHandler now also asserts the write buffer is empty for 204 responses

Allow 204 responses without Content-Length/Transfer-Encoding

---

tornado/test/web_test.py
tornado/web.py

Fixes a regression in version 4.4
Fixes #1770

web: URLs that cannot be unescaped should be allowed

---

tornado/http1connection.py
tornado/test/httpserver_test.py

As per [RFC 2616 section 3.6](https://tools.ietf.org/html/rfc2616#section-3.6), "Transfer-Encoding" header's value is case-insensitive.
It turned out that Cocoa's NSURLConnection sends `Transfer-Encoding: Chunked` (starting with a capital letter), which makes Tornado ignore the actual request body.

Fix for uppercase "Transfer-Encoding" values

---

tornado/platform/asyncio.py

sphinx-build was warning us, "reference target not found: asyncio.BaseEventLoop.add_reader"

Update reference to asyncio's add_reader doc

---

tornado/netutil.py

Of course I had to copy the typoed string into my code :).

Fix "resuse_port" typo in documentation

---

tornado/test/import_test.py

When I read the import_test.py, I found out the the import test for tcpclient is missing. This PR add the missing import check.
- Add test for import tcpclient
- Remove comment line.

Add import tcpclient test in import_test

---

tornado/gen.py
tornado/test/gen_test.py

This changeset fixes #1769 to my satisfaction (and I hope everyone else's).
My changeset causes the `gen.coroutine` (and `gen.engine`, I think) to keep a `WeakKeyDictionary` mapping result futures to `Runner` objects. This `WeakKeyDictionary` is ~~closured to the coroutine generator function itself~~ a global.
The resulting behavior is that, if there exists hard references to the result future object ~~*and* to the coroutine function~~, the `Runner` object will not die.
**Everything below is no longer relevant but I'm keeping it for historical reasons**
In addition, I added a `__del__` method to the `Runner` object (In Python > 3.4 only) which causes it to "cancel" (load with an exception, since tornado's futures don't have cancel semantics) the result future if the `Runner` is collected …

Tie Runner lifetime to lifetime of result future or coroutine function (whichever is GCed first)

---

tornado/tcpclient.py

e.g. trying to connect to IPv6 addresses on OSes with IPv6 disabled
This fixes #1809

tcpclient: try next address when protocol not supported

---

tornado/ioloop.py
tornado/test/ioloop_test.py

Fixes #1803 by preventing _run_callback from directly calling
add_callback again when a callback returns {} or [].

io_loop: Don't spin CPU if callback returns {}

---

docs/releases.rst
docs/releases/v4.4.2.rst
setup.py
tornado/__init__.py
tornado/httputil.py
tornado/platform/asyncio.py
tornado/test/httputil_test.py
tornado/test/web_test.py

Move from the python standard library to a parsing function copied from
Django. This parser more closely matches browser behavior. The primary
motivation is that differences between server-side and browser cookie
parsing can lead to an XSRF bypass, as in
https://hackerone.com/reports/26647. A secondary benefit is that this
makes it possible to work with cookie headers containing cookies that
are invalid according to the spec, which is a surprisingly common
request.
Closes #1851 
Closes #633
Closes #1434
Closes #1176

httputil: Rewrite cookie parsing

---

tornado/ioloop.py
tornado/platform/common.py
tornado/platform/interface.py
tornado/platform/posix.py

Lockless implementation of add_callback

---

docs/guide/structure.rst
tornado/test/web_test.py
tornado/web.py

The docs had wrongly claimed this was supported before. Implement it,
and update the docs to show the str.format-style syntax we chose.
Closes #1861.

web: Add regex support to RedirectHandler

---

docs/gen.rst
tornado/gen.py
tornado/test/gen_test.py

This PR ensures the `__wrapped__` attribute of a coroutine points to the original function, and it also adds a utility function to know whether a function is a coroutine.
The initial motivation stems from the complications encountered in https://github.com/dask/distributed/pull/673.

Improve introspection of coroutines

---

tornado/concurrent.py
tornado/test/concurrent_test.py
tornado/test/util_test.py
tornado/util.py

When there are still active coroutines at interpreter shutdown, you can see sometimes warnings such as:
```
Exception ignored in: <bound method Future.__del__ of <tornado.concurrent.Future object at 0x7f56a8b142e8>>
Traceback (most recent call last):
File "/home/antoine/tornado/tornado/concurrent.py", line 338, in __del__
TypeError: 'NoneType' object is not callable
```
These are distracting and don't bear any useful information, so silence them.

Avoid spurious warnings at shutdown

---

tornado/tcpserver.py
tornado/test/tcpserver_test.py

If called a second time, `TCPServer.stop` could call `remove_handler()` with its file descriptors *again*, which really means unregistering the file descriptors of non-TCPServer sockets (since the average Unix system will tend to re-use fd numbers), leading to obscure bugs.

Fix #1901: fix TCPServer.stop() when called twice

---

tornado/netutil.py

netutil: Preload the "latin1" codec
For reasons not yet understood, some Solaris users get intermittent
"LookupError: unknown encoding: latin1", this has been reported to
fix it.
Fixes #584

netutil: Preload the "latin1" codec

---

tornado/process.py

```
=================================== ERRORS ====================================
______________________________ ERROR collecting  ______________________________
.tox\tox\lib\site-packages\py\_path\common.py:332: in visit
for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
.tox\tox\lib\site-packages\py\_path\common.py:378: in gen
for p in self.gen(subdir):
.tox\tox\lib\site-packages\py\_path\common.py:368: in gen
if p.check(dir=1) and (rec is None or rec(p))])
.tox\tox\lib\site-packages\_pytest\main.py:670: in _recurse
ihook = self.gethookproxy(path)
.tox\tox\lib\site-packages\_pytest\main.py:575: in gethookproxy
my_conftestmodules = pm._getconftestmodules(fspath)
.tox\tox\lib\site-packages\_pytest\config.py:339: in _getconftestmodules
mod = self._importconftest(conftestpath) …
```

Catch AttributeError in cpu_count()

---

tornado/tcpserver.py
tornado/test/tcpserver_test.py

Discovered here:
http://stackoverflow.com/questions/40239901/tornado-tcp-server-client-process-communication/40257248?noredirect=1#comment69144882_40257248
and here:
http://stackoverflow.com/questions/40968271/async-with-tornado-tcpclient-and-tcpserver/40973556

tcpserver: handle_stream can be a native coroutine

---

docs/releases/v2.3.0.rst
docs/releases/v3.2.0.rst
docs/routing.rst
docs/webframework.rst
tornado/httputil.py
tornado/routing.py
tornado/test/routing_test.py
tornado/test/runtests.py
tornado/test/web_test.py
tornado/web.py

In Tornado 3, the handler specified in URLSpec could be of any callable type, which allowed to implement custom routing just like that:
``` python
self.add_handlers('.*$', [
(r'.*', app_router)
])
```
where `app_router` contained some logic for providing an appropriate handler instance.
With Tornado 4 this is unfortunately impossible (all handlers must subclass `RequestHandler`) and the simplest way to achieve relatively the same is to subclass `_RequestDispatcher` to extend `_find_handler` method and use this custom dispatcher in `Application.start_request`.
This seems hacky enough for me, so I suggest adding the legal way to extend routing mechanism in Tornado.
The main ideas:
- move all routing logic (`Application.[_get_host_handlers, add_handlers, reverse_url]`, …

implement routing mechanism

---

tornado/httputil.py
tornado/test/httputil_test.py

If there is a fragment in the original url, there will be some problem with url_concat function.   
Like: 
>>> url_concat('http://ex.com/path#tab', dict(a='a'))
'http://ex.com/path#tab?a=a'
It seems better that using python urllib & urlparse libraries instead of spelling it ourself.   
"Don't Reinvent The Wheel."
The New implementation accept not-strictly url formating(like `http://ex.com?x&y=y`) and converting it to standard one (`http://ex.com?x=&y=y`).

Rewrite url_concat function using PythonStandardLibrary

---

.travis.yml
setup.py
tox.ini

Python 3.6.0 is the newest major release of the Python language, and it contains many new features and optimizations.
Add it to CI configuration files and add latest python versions (3.5 and 3.6) to setup.py

Add Python 3.6 support

---

docs/conf.py

Because PyPI has changed the download url rules, the download url on document has broken.
Before the download url is
```
https://pypi.python.org/packages/source/t/tornado/tornado-4.4.2.tar.gz
```
After change 
```
https://pypi.org/packages/source/t/tornado/tornado-4.4.2.tar.gz
```
The new format should have a long term support: https://bitbucket.org/pypa/pypi/issues/438.
And [pypi.org](https://pypi.org/) is PyPI 2.0's domain name.

Fix document PyPI download url

---

tornado/http1connection.py

I kept misspelling "response" in my own project's docstrings and upon grepping to make sure it was totally wiped out, discovered it was also misspelled in here. Clearly the word has been misspelled since it's inception, but since we can't change English, let's update it here.

Documentation Typo

---

tornado/web.py

As discussed in issue #1652, these methods will allow developers to define how the final rendering of the JS and CSS assets should be handled without having to overwrite too much RequestHandler code.

Moved the rendering of CSS and JS assets to their own instance methods

---

tornado/iostream.py
tornado/test/iostream_test.py

Replace the deques of chunks in IOStream with simple bytearrays. This simplifies and optimizes buffer management, removing many extraneous copies.
Also allow a memoryview as `write()` argument, as that's useful to avoid copies in applications.
Seems to fix #1685. @mrocklin

Use bytearray buffers in IOStream

---

tornado/websocket.py

Fixes #938 
This fixes the problem of exceptions being swallowed in websocket client on_message callbacks. As @bdarnell pointed out in the issue, there should be some changes made to WebSocketProtocol to know what attributes it does and does not have, but this will at least prevent the `AttributeError` which causes the callback to silently be called again with `None` whenever any exceptions are raised in the original callback.

websocket: fix client message callback error

---

tornado/log.py

see also [this issue](https://github.com/tornadoweb/tornado/issues/1960)
Use it the right way is as follows
```python
#!/usr/bin/env python3
import logging
import logging.config
logging.config.dictConfig({
'version': 1,
'incremental': False,
'disable_existing_loggers': False,
'formatters': {
'color_formatter': {
'class': 'tornado.log.LogFormatter',
'format': '%(color)s[%(levelname)1.1s %(asctime)s %(module)s:%(lineno)d]%(end_color)s %(message)s',
'datefmt': '%y%m%d %H%M%S',
},
},
'handlers': {
'color_handler': {
'class': 'logging.StreamHandler',
'formatter': 'color_formatter',
},
},
'loggers': {
'mylogger': {
'level': 'DEBUG',
'handlers': ['color_handler'],
},
},
})
logger = logging.getLogger('mylogger')
logger.debug("message")
logger.info("message")
logger.warn("message") …
```

Make `tornado.log.LogFormatter` compatible with `logging.config.dictConfig`.

---

tornado/httpserver.py

regarding: #641
Currently passing `no_keep_alive=True` to HTTPServer.init while also including "Connection: Close" header in responses does not terminate connections server-side. It seems for the intended behavior to work, `no_keep_alive` options needs to be passed through to the server's HTTP1ConnectionParameters.

HTTPServer pass no_keep_alive option to conn params

---

tornado/autoreload.py

This was a last-ditch effort to close file descriptors that were not
marked as CLOEXEC. However, it was never complete (it didn't touch
file descriptors that were not registered on the IOLoop), and it can't
work with asyncio (which does not allow closing the IOLoop without
stopping it and unwinding the stack first). Since Tornado (and
hopefully all major libraries using the IOLoop) is careful about
setting CLOEXEC when needed, just get rid of the close.
Fixes #1543

autoreload: Don't close the IOLoop on reload

---

tornado/websocket.py

This pull-request adds support for specifying compression_level and mem_level to WebSocketHandler.get_compression_options(). 
These parameters are documented here: https://docs.python.org/3.6/library/zlib.html#zlib.compressobj
The default compression level is currently 6, but sometimes it can be useful to configure this to some other value. I have not tried to make wbits configurable, that would be more complex.

Add compression_level and mem_level to WebSocketHandler.get_compression_options()

---

tornado/log.py

This is a slight rework of #1487 which was closed when I reorganized my clone. I'm not sure what the proper way to test this would be, but I used the following script to visually check that the output does as expected:
``` python
import logging
from tornado.log import enable_pretty_logging
logger = logging.getLogger()
enable_pretty_logging()
logger.setLevel(logging.DEBUG)
logger.info("INFO")
logger.warning("WARNING")
logger.debug("DEBUG")
logger.error("ERROR")
print("normal")
```

Enable color logging on Windows via colorama

---

tornado/httpserver.py
tornado/test/httpserver_test.py

This is an attempt to address the limitation whereby only the closest host in the `X-Forwarded-For` header may be used as the remote ip address.  The developer may now specify a list of trusted downstream proxy hosts that will be skipped in parsing the X-Forwarded-For header.
This is analogous to similar functionality offered by Squid and Nginx.  I discussed this in ticket #1840.  I'll create a separate PR for proxies that include their connection port in their `X-Forwarded-For` entry.

Allow specificion of trusted downstream proxies for xheaders

---

tornado/websocket.py

This is not allowed for native coroutines, although for reasons I
can't put my finger on it only fails intermittently (in the one test
we have that uses this with native coroutines).

websocket: Avoid calling convert_yielded twice on the same object

---

tornado/ioloop.py

avoids modifying dict during iteration if close method on fd triggers something like `IOLoop.remove_handler`, which can happen on Python 3 (not Python 2, where `dict.values()` is already a copy).
This is coming up in https://github.com/zeromq/pyzmq/issues/963, where FutureSocket calls `io_loop.remove_handler(self)` in close.

copy handler list in IOLoop.close(all_fds=True)

---

docs/websocket.rst
tornado/test/websocket_test.py
tornado/websocket.py

A new method, upgrade_response_headers, is introduced to WebSocketHandler that a user can override to return custom headers in the websocket upgrade response.

Allow custom websocket upgrade response headers

---

tornado/auth.py
tornado/test/auth_test.py

This was recently broken by the move from url-encoding to json.
Closes #2001

auth: Update, doc, and test the facebook session_expires field

---

tornado/httputil.py
tornado/test/httputil_test.py

A change made in 4.5 to the `url_concat` function broke some assumptions used in external code.
Notably, in SaltStack, this breaks parsing for some states people are using in production. See this issue: https://github.com/saltstack/salt/issues/40749
This patch fixes that external code to once again allow `url_concat("foo", None)` and adds a test to check this behavior.
My first time contributing - let me know if I missed something big. 
Thanks!

fix backwards compatibility of url_concat for args=None

---

tornado/log.py

The previous logic would fail whenever curses is missing (which is
always true on windows, and is occasionally true on other platforms)
and colorama is installed but not initialized in this process (this is
a common occurrence for users of jupyter and ipython on windows).
Fixes #2013
Fixes #2015 
cc @mivade

log: Fix color logging detection

---

demos/file_upload/file_uploader.py

If no filenames are specified then [the demo prints to standard error](/tornadoweb/tornado/blob/26e5779a50b466f8e2a5bf14808c96ebea2a4eef/demos/file_upload/file_uploader.py#L111), but it uses a syntax only compatible with Python 3 unless the print function is imported from `__future__`.

Fix file upload demo on Python 2.

---

tornado/curl_httpclient.py

The `CurlAsyncHTTPClient` will cause memory leak when set `force_instance=True`,because the `self._multi` and `self._force_timeout_callback`hold some methods that belong the instance of `CurlAsyncHTTPClient`,it will cause circular reference.
Here is the test code:
```python
#!/usr/bin/env python
""" """
from __future__ import print_function, division, unicode_literals
import sys
from tornado.curl_httpclient import CurlAsyncHTTPClient
class Demo(object):
def __init__(self):
self._client = CurlAsyncHTTPClient(force_instance=True)
def __del__(self):
print(sys.getrefcount(self._client))        # 5
self._client.close()
print(sys.getrefcount(self._client))        # 5 (The reference count is not change)
self._client._force_timeout_callback.callback = None
print(sys.getrefcount(self._client)) …
```

Fix CurlAsyncHTTPClient cause memory leak with `force_instance=True`

---

tornado/speedups.c

This change includes the optimization of `websocket_mask` function which is written in C extension.
Basically the idea is from the cython implementation of another popular Python web framework - aiohttp. (https://github.com/aio-libs/aiohttp/blob/v1.2.0/aiohttp/_websocket.pyx)
Here is a benchmark result (CPython 3.5.1):
```sh
% python -m timeit \
-n 100000 \
-s 'import os; from tornado.speedups import websocket_mask; mask = b"asdf"; data = os.urandom(100 * 1024)' \
'websocket_mask(mask, data)'
100000 loops, best of 3: 113 usec per loop
% python -m timeit \
-n 100000 \
-s 'import os; from tornado.speedups import websocket_mask; mask = b"asdf"; data = os.urandom(100 * 1024)' \
'websocket_mask(mask, data)'
100000 loops, best of 3: 23.1 usec per loop
```
The change takes more advantages if the …

websocket: optimize C websocket_mask function

---

tornado/web.py

Be explicit that get_cookie cannot see the cookies set within the
current request, avoiding confusion as seen in #1993

web: Clarify cookie method docs

---

appveyor.yml

Only run partial tests in two of the four environments.

build: Speed up appveyor tests by not running the full matrix.

---

tornado/test/testing_test.py
tornado/testing.py

Extends the `AsyncHTTPTestCase.fetch` method to allow for the fetching of a path as-is instead of appending it to the Tornado instance. Useful when testing against external services.

Fetch absolute URL in AsyncHTTPTestCase

---

tornado/ioloop.py
tornado/platform/twisted.py
tornado/test/twisted_test.py
tornado/test/util_test.py
tornado/util.py

This makes it possible to construct a PollIOLoop even when the default
IOLoop is configured to something else.

ioloop: Make PollIOLoop separately configurable

---

tornado/netutil.py
tornado/platform/common.py
tornado/tcpclient.py

PR #1984 was based on the mistaken belief that we were already
doing this (and in python 3.4+, it's true, thanks to PEP 446). This
fixes a regression introduced in Tornado 4.5 in which autoreload would
leak file descriptors and leave client connections hanging.
Fixes #2057

tcpclient,netutil: Set FD_CLOEXEC on all sockets created by Tornado

---

docs/ioloop.rst
tornado/ioloop.py
tornado/testing.py

This aligns us more closely with asyncio, which only has a single
get_event_loop() function. Most uses of instance() are simply a
holdover from before current() was introduced and are not actually
relying on its slightly different behavior, so we redefine it (and the
related methods install(), initialized(), and clear_instance()) in
terms of current().

ioloop: Redefine instance() in terms of current()

---

.travis.yml
tornado/ioloop.py
tornado/test/httpclient_test.py
tornado/test/ioloop_test.py
tornado/test/process_test.py
tox.ini

In addition to changing the configurable default, add a special case
in IOLoop.current() so that the current IOLoop will be backed by
the main asyncio event loop.

ioloop: Make asyncio the default when available

---

tornado/http1connection.py
tornado/httputil.py
tornado/test/httpserver_test.py

This closes #1082 by returning a HTTP 400 (and then closing the connection) when the server encounters a bad request line instead of closing the connection immediatley.

Return HTTP 400 on bad request lines

---

tornado/http1connection.py
tornado/httpserver.py
tornado/test/httpserver_test.py

When HTTP1Connection acts as the server, it closes the connection
after writing the response if the client includes the
"Connection: close" header in the request, or if the `no_keep_alive`
option is set to True in the constructor.
According to https://tools.ietf.org/html/rfc7230#section-6.6
> The server SHOULD send a "close" connection option in its final
response on that connection.
It was possible for an Application to set the Connection header
appropriately. But it is very helpful for tornado to take care of
this automatically, particularly if "close" was specified in a
request header.
fixes #2071

http1connection: add "Connection: close" header if appropriate

---

tornado/autoreload.py
tornado/test/autoreload_test.py
tornado/test/import_test.py
tornado/test/runtests.py

The fix works for Python >= 3.4, keeping the current workaround for previous
versions. Also introduce a first unit test for autoreload. Close #2044.

Fix module autoreload for __main__ with relative imports

---

tornado/tcpclient.py
tornado/test/tcpclient_test.py

Hi bdarnell, I fixed some issues you mentioned last time.
1) The `tcpclient` timeout parameter should be real numbers or `timedelta`.
2) Add precise timeout testing to `tcpclient`.
3) Pass timeout to `connector`. If the timeout is triggered, we will not iterate either next address or secondary address, and the later success stream will also be closed.

Tcpclient connect timeout

---

tornado/curl_httpclient.py

since they come in as bytes on Python 3

cast pycurl debug messages to str

---

tornado/curl_httpclient.py

This PR exposes the duration from the start until the SSL/SSH connect/handshake to the remote host timing (1).
libcurl/PycURL compatibility:
The option was added in libcurl 7.19.0, Tornado stable requires 7.22.0 or higher, PycURL requires 7.19.0 or higher.
runtest.sh is passing on my dev environment but happy to do more testing as need be.
(1) https://curl.haxx.se/libcurl/c/CURLINFO_APPCONNECT_TIME.html

Add SSL/SSH handshake timing to response properties (curl client)

---

tornado/httputil.py
tornado/test/httputil_test.py

In tornadoweb/tornado#1112 it was decided to stop including headers in the request repr, since they are needlessly verbose and risk leaking user secrets into the application log.

Remove headers from HTTPServerRequest repr

---

tornado/autoreload.py

After the removal of the deprecated `io_loop` arguments from all functions, the autoreload module stopped working as the wait function's usage was missed in the refactor. This resulted in the start function receiving an `IOLoop` object as its only argument which it then used as the `check_time` argument resulting in errors further down the line when the `check_time` is expected to be an int. This PR fixes that problem allowing the autoreload script to work correctly.
To the see the original bug just run the autoreload module, for example: `python -m tornado.autoreload -m tornado.test`, modify a test file after the first run completes and you'll get something like this:
```
[I 170819 12:02:37 testing:679] PASS
[I 170819 12:02:37 autoreload:306] Script exited with status False
Traceback …
```

Correctly clear and create a new ioloop during autoreload

---

demos/file_upload/file_uploader.py

The documentation for `tornado.httpclient.HTTPRequest` says:
> body_producer – Callable used for lazy/asynchronous request bodies. It is called with one argument, a write function, and should return a Future. It should call the write function with new data as it becomes available. The write function returns a Future which can be used for flow control.
In the simpler example in this demo, `raw_producer()`, there are no yields (or awaits) at all. It doesn't make much sense to use a `body_producer` callback if it generates and writes the whole body all at once without ever yielding, you might as well have just generated the whole body up front. In the more complex example, `multipart_producer()`, it looks like `yield gen.moment` was thrown in to allow some of the body to be sent before more …

file_upload demo: yield write() cb in body_producer

---

tornado/test/websocket_test.py
tornado/websocket.py

Missing web socket header causes an exception because _abort function tries to close `stream` if there is yet stream before the handshaking.
This PR changes _abort function to return HTTP 400 error when the handshaking is not completed (a.k.a stream is None).
Fixes #2156

websocket: fix missing websocket header causes an exception

---

tornado/ioloop.py
tornado/test/ioloop_test.py

Addresses #1982: implements an API mimicking `run_in_executor` from `asyncio`. This uses the same strategy as `asyncio`, namely using `chain_future` to map `concurrent.futures.Future` onto an awaitable `Future`.
Some questions:
- Do we need to do something else to properly handle exceptions here?
- What additional tests should be added?
- Would it make sense to always return the chained future instead of checking the Python version?

Implement IOLoop.run_in_executor

---

docs/index.rst
maint/requirements.in
setup.py
tornado/iostream.py
tornado/netutil.py
tornado/simple_httpclient.py
tornado/test/httpserver_test.py
tornado/test/iostream_test.py
tornado/test/runtests.py
tornado/test/simple_httpclient_test.py
tornado/test/twisted_test.py
tornado/test/util.py

Drop support for pre-2.7.9 (and pre-3.4) versions of the `ssl` module. 
Also clean up some vestigial workarounds for py26.

Require modern SSL features

---

tornado/iostream.py

All recent Python versions (including recent Python 2.7 updates) set SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER on OpenSSL sockets, so we needn't freeze the write buffer anymore.

Remove SSL hack

---

tornado/ioloop.py
tornado/test/ioloop_test.py

Correctly transform the concurrent Future into a Tornado Future
and test that the result is usable with await.
cc @mivade (chain_future was in your initial implementation but I think I gave you some confusing feedback and it got lost along the way)

Fixes for IOLoop.run_in_executor

---

tornado/ioloop.py
tornado/test/ioloop_test.py

See motivation at https://github.com/dask/distributed/pull/1172

Fetch IOLoop in PeriodicCallback.start(), not __init__()

---

demos/webspider/webspider.py

An invalid byte currently stops the webspider. For instance, try it with `https://www.google.com` and you will get the following result:
```
$ python webspider.py
fetching https://www.google.com
fetched https://www.google.com
Exception: 'utf-8' codec can't decode byte 0xe7 in position 44372: invalid continuation byte https://www.google.com
Done in 0 seconds, fetched 1 URLs.
```
Solution: Ignore bad bytes and keep on crawling :)

Don't let invalid bytes stop the Webspider demo

---

tornado/test/simple_httpclient_test.py
tornado/test/util.py
tornado/test/web_test.py
tornado/testing.py

There are many ways ipv6 can be disabled or broken (and it just
stopped working on travis-ci), so instead of checking flags like
socket.has_ipv6, attempt to actually bind to an ipv6 address.
Closes #2185

test: More robust avoidance of broken ipv6

---

.travis.yml
docs/concurrent.rst
docs/conf.py
docs/guide/security.rst
tornado/auth.py
tornado/concurrent.py
tornado/gen.py
tornado/http1connection.py
tornado/httpclient.py
tornado/ioloop.py
tornado/iostream.py
tornado/locks.py
tornado/platform/asyncio.py
tornado/platform/twisted.py
tornado/queues.py
tornado/tcpclient.py
tornado/test/asyncio_test.py
tornado/test/concurrent_test.py
tornado/test/curl_httpclient_test.py
tornado/test/gen_test.py
tornado/test/httpserver_test.py
tornado/test/ioloop_test.py
tornado/test/locks_test.py
tornado/test/runtests.py
tornado/test/tcpclient_test.py
tornado/test/tcpserver_test.py
tornado/test/twisted_test.py
tornado/testing.py
tornado/websocket.py
tox.ini

Tornado's Future class is now an alias for asyncio.Future on python 3.4+.
- Removed TracebackFuture alias
- Introduced new functions future_set_exc_info and future_add_done_callback to cover some differences between the implementations
- Tweaked tests due to changes in callback timing (asyncio futures always schedule their callbacks on the next IOLoop iteration)
- Ensure all tests have valid asyncio event loops (asyncio.Future requires one *at creation time*)

concurrent: Use asyncio.Future when available

---

tornado/gen.py
tornado/test/gen_test.py

When in debug mode, asyncio returns the instantiation place of a Future
and places it in its repr(), for example:
`<Future finished result=None created at /home/antoine/distributed/distributed/worker.py:1223>`
This is useful when asyncio logs cancelled futures or futures that were not
waited upon after erroring out.
However, when using @gen.coroutine, we need to fix the recorded stack trace
otherwise the display is much less useful:
`<Future finished result=None created at /home/antoine/tornado/tornado/gen.py:295>`

Improve debug support for asyncio futures

---

maint/circlerefs/circlerefs.py
tornado/gen.py
tornado/web.py

Similar to https://github.com/tornadoweb/tornado/pull/1936 I discovered that there are some circular references remain when RequestHandler raises HttpError or Finish:
```python
class DummyAsyncHandler(web.RequestHandler):
@gen.coroutine
def get(self):
raise web.Finish('ok\n')
```
Without changes:
```
GC disabled
Start on 8888
gc: collecting generation 2...
gc: objects in each generation: 704 0 10586
gc: done, 56 unreachable, 0 uncollectable, 0.0054s elapsed.
Collected: 56
Garbage: 55
```
With changes:
```
GC disabled
Start on 8888
gc: collecting generation 2...
gc: objects in each generation: 645 0 10586
gc: done, 0.0046s elapsed.
gc: collecting generation 2...
gc: objects in each generation: 1 0 10757
gc: done, 0.0044s elapsed.
Collected: 0
Garbage: 0
```

Break circular references when async request handler raises exception

---

tornado/iostream.py
tornado/test/iostream_test.py

Improves performance by 35% on the following benchmark: https://github.com/tornadoweb/tornado/issues/2147#issuecomment-329146253
Makes `demos/benchmark/benchmark.py` about 2% slower.
(split from https://github.com/tornadoweb/tornado/pull/2166)

Issue #2147: avoid copies on non-small writes

---

tornado/httpserver.py
tornado/test/httpserver_test.py

use the first entry, which should be the outermost value
closes #2161

handle multiple values in X-Forwarded-Proto

---

tornado/ioloop.py

Currently, the example code in the document [Main event loop](http://www.tornadoweb.org/en/stable/ioloop.html#tornado.ioloop.IOLoop) has some errors when trying to copy-paste-run it, it's not completed.
It obviously can demonstrate the usage of ioloop, but maybe it's better to make it can run directly.

Make the example code in the document "tornado.ioloop — Main event loop" can copy-paste-run directly.

---

tornado/gen.py
tornado/ioloop.py
tornado/test/ioloop_test.py
tornado/testing.py

Coroutines using `await`/`yield from` are more tightly coupled than coroutines using `yield`; they must all share the same coroutine. The asyncio task runner publishes some non-local state that common libraries rely on, so these libraries could not be used in native coroutines that were started by tornado (aio-libs/aiohttp#877). Address this by using the asyncio task runner everywhere.

gen: Use the asyncio task runner for native coroutines

---

tornado/ioloop.py
tornado/platform/asyncio.py
tornado/test/asyncio_test.py
tornado/test/twisted_test.py
tornado/testing.py

This should eliminate the need for explicit asyncio manipulations
from applications migrating to Tornado 5.0
cc @pitrou @mrocklin @bryevdv

ioloop: Setting AsyncIOLoop as current also sets asyncio event loop

---

docs/concurrent.rst
docs/conf.py
docs/guide/async.rst
docs/integration.rst
docs/ioloop.rst
docs/releases.rst
docs/releases/v4.5.2.rst
docs/releases/v5.0.0.rst
tornado/concurrent.py
tornado/gen.py
tornado/httputil.py
tornado/ioloop.py
tornado/platform/asyncio.py
tornado/tcpclient.py
tornado/testing.py
tornado/util.py
tornado/web.py

Update versionadded/versionchanged tags. Misc other doc updates

docs: Start release notes for 5.0.

---

tornado/gen.py
tornado/queues.py
tornado/tcpserver.py
tornado/test/tcpserver_test.py

Two recent changes broke Tornado's multiprocess modes by initializing
the event loop before the fork in typical patterns.
- The removal of `io_loop` arguments moved a call to
IOLoop.current() earlier in TCPServer's constructor.
- The change to `asyncio.Future` initialized the asyncio event loop at
import time.
Move the call in TCPServer earlier (and audit the rest of that change
to make sure this didn't happen anywhere else) and replace
`gen.moment` and `gen._null_future` with dummy objects that do not
involve the asyncio event loop.

tcpserver: Fix multiprocess modes

---

.travis.yml
docs/guide/async.rst
docs/index.rst
docs/releases/v5.0.0.rst
setup.py
tornado/netutil.py
tornado/platform/asyncio.py
tornado/platform/twisted.py
tox.ini

`concurrent.futures` is now required on python 2.

netutil: Use a threaded resolver by default

---

tornado/http1connection.py
tornado/test/httpserver_test.py
tornado/test/web_test.py

otherwise a subsequent request on the same connection will fail to be parsed
thanks to @eeelin for the bug report
I have an interest in #2194 so this is my attempt to complete it.
I also hope this can be cherry-picked into tornado-4.5 for a patch release.

http: read final crlf of chunked requests

---

tornado/http1connection.py

bug introduced in #2225 
Not noticed because no test hit the error case ... 🤦‍♂️

fix HTTPInputError reference for improperly terminated chunked request

---

tornado/iostream.py

bug introduced in #2028
this fix very similar to #2155 
No, I didn't actually run into this ... I was just trolling through merged PRs looking for candidate small fixes to suggest for the 4.5 branch. (#2028 is perhaps a bit too big to qualify)

fix iostream exc_info using missing Exception var

---

tornado/auth.py

Google's documentation provides different URLs for oauth so it might be a good idea to update
See: https://developers.google.com/identity/protocols/OpenIDConnect
Work fine for me :)

update google oauth URLs

---

tornado/locks.py

~~The [documentation](http://www.tornadoweb.org/en/stable/locks.html#tornado.locks.Condition) for condition is misleading.  In the class docs, it depicts the `wait` method to accept a timeout, and once the timeout has elapsed raise a `gen.TimeoutError` much like how `Event`, `Lock`, and `Semaphore` all raise.  However, the literal [method](http://www.tornadoweb.org/en/stable/locks.html#tornado.locks.Condition.wait) changes the classes defined behavior of wait to a unique action of setting the `Future` to `False`.~~
~~This PR aims to make `Condition` act more like it's `tornado.locks` brethren by setting the `gen.TimeoutError` exception when the timeout has elapsed.~~
**Edit:** Changed the PR to alter documentation to reflect the methods behavior, rather than alter the method to fit the …

Alter Condition.wait() documentation.

---

tornado/gen.py
tornado/ioloop.py
tornado/platform/asyncio.py
tornado/test/concurrent_test.py
tornado/test/gen_test.py
tornado/test/ioloop_test.py

Ensure that after an IOLoop is closed, any coroutines running on it are able to be GC'd. Improve management of the "current" IOLoop and correspondence with the asyncio loop to ensure that we don't orphan an asyncio event loop without closing it (or leaving it as current). 
Includes a rebase of #2230 
Closes #2230 
Fixes #2229 
Fixes #2240

ioloop,gen,asyncio: Improvements to IOLoop GC

---

tornado/iostream.py
tornado/process.py
tornado/test/iostream_test.py
tornado/test/netutil_test.py
tornado/test/process_test.py
tornado/test/runtests.py
tornado/test/testing_test.py
tornado/testing.py

This makes the implementation of PipeIOStream more compatible with
socket streams, and allows for more of the test suite to be used with
it.
Extracted from PR #2193. This was an uncontroversial part of the change but a large diff that could land separately.  cc @pitrou

iostream: Use file objects instead of raw descriptors in PipeIOStream

---

docs/ioloop.rst
docs/releases/v5.0.0.rst
tornado/ioloop.py
tornado/platform/asyncio.py
tornado/process.py
tornado/test/ioloop_test.py
tornado/test/process_test.py

Instead of a redundant IOLoop._current thread-local, pass through
directly to asyncio and maintain a one-to-one mapping of asyncio loops
to IOLoops. This brings us a bit closer to the asyncio-only future.
Also remove IOLoop.initialized(). It is no longer possible to provide this method with reasonable
semantics.

ioloop: current() and friends delegate to asyncio

---

tornado/test/httpclient_test.py
tornado/test/httpserver_test.py
tornado/test/routing_test.py
tornado/test/websocket_test.py

Some recently-introduced tests are failing under tornado_http2, so fix
them.

test: Adjust unittest for tornado_http2 compatibility

---

tornado/gen.py
tornado/test/gen_test.py

fixes assertion in gen.multi when calling convert_yielded with more than one gen.moment or None
convert_yielded can be called with None or [None]. When it is called with [None], gen.multi gets [gen.moment], which fails assert(is_future) now that gen.moment is no longer a real Future.

fix gen.multi with gen.moment

---

tornado/curl_httpclient.py

Some debug messages are binary blobs that should not be decoded.
Fixes #2275 
Since the native_str change was backported to 4.5.3, this fix should go into 4.5.4 (if there is one)

curl_httpclient: Only call native_str on debug message when needed

---

docs/conf.py
docs/releases/v5.0.0.rst
tornado/httpclient.py
tornado/log.py
tornado/web.py

This introduced a new inherit-docstring option that we don't want
(it currently breaks our docs build) and got stricter about `:arg`
types.

docs: Updates for sphinx 1.7

---

tornado/gen.py
tornado/ioloop.py
tornado/platform/asyncio.py
tornado/test/asyncio_test.py

The ensure_future function was not introduced until 3.4.4, and
some exceptions were changed from AssertionError to RuntimeError in
3.4.3.
Fixes #2301

asyncio: Support Python 3.4.2 for compatibility with Debian jessie

---

tornado/gen.py
tornado/ioloop.py
tornado/platform/asyncio.py
tornado/test/asyncio_test.py

The ensure_future function was not introduced until 3.4.4, and
some exceptions were changed from AssertionError to RuntimeError in
3.4.3.
Fixes #2301

cherrypick-5.0: asyncio: Support Python 3.4.2 for compatibility with Debian jessie

---

tornado/test/testing_test.py
tornado/testing.py

This improves compatibility with asyncio test frameworks like
pytest-asyncio.
Fixes #2324

testing: Don't close the event loop if we didn't create it

---

tornado/ioloop.py
tornado/test/ioloop_test.py

This commit addresses two issues:
1. If the clock moves backwards a little bit, we could run a
PeriodicCallback twice in a row.
Due to implementation differences between the Tornado and asyncio
event loops, this is most common when using the asyncio event loop on
windows, although it can in principle occur in any environment.
2. If the clock moves backwards by a lot, the PeriodicCallback would
effectively be disabled until the clock catches up with its former
value.
This commit Fixes the second issue for the asyncio loop (which uses
a monotonic clock internally) but not for the legacy Tornado IOLoops
(which use time.time() internally).
Fixes #2333

ioloop: Fix PeriodicCallback when system clock moves backwards

---

docs/httpclient.rst
tornado/auth.py
tornado/httpclient.py
tornado/platform/caresresolver.py
tornado/simple_httpclient.py
tornado/test/curl_httpclient_test.py
tornado/test/httpclient_test.py
tornado/test/httpserver_test.py
tornado/test/runtests.py
tornado/test/simple_httpclient_test.py
tornado/test/stack_context_test.py
tornado/test/tcpclient_test.py
tornado/test/testing_test.py
tornado/test/web_test.py
tornado/testing.py
tox.ini

In 6.0, the `callback` argument to `fetch` will be going away as a part of the general move towards pure coroutines. The behavior of `raise_error=False` will also change to reduce the use of fake 599 response codes (which were mainly used to get around the limitations of the callback interface).
Deprecation warnings were added for both of these changes. This caused a fair amount of churn in the test suite, although hopefully less in applications that aren't doing as much probing of HTTP edge cases.

httpclient: Deprecate fetch callback, narrow `raise_error`

---

tornado/ioloop.py
tornado/test/ioloop_test.py

A performance issue I have run into in several tornado applications is alignment of callbacks under load, causing brief periods of unresponsiveness at regular intervals, e.g. several similar PeriodicCallbacks aligning so that they fire in the same eventloop iteration. A solution that I have applied on a number of occasions is adding jitter to my periodic events, to reduce the occurrence of alignment. I thought it might be nice to support this in the default PeriodicCallback class.
`jitter` is a fraction and `callback_time` is used as the lower bound, so callbacks are scheduled on the interval
```python
[callback_time, callback_time * (1 + jitter)]
```

Support jitter in PeriodicCallback

---

tornado/websocket.py

Replaces the `deque` in the websocket client with a tornado `Queue`, as per @bdarnell 's suggestion.
This fixes https://github.com/tornadoweb/tornado/issues/2341

Fix out of memory issue with websocket client

---

appveyor.yml
tornado/test/simple_httpclient_test.py

This test required some refactoring to construct invalid headers that
we no longer allow handlers to return directly.

test: Reinstate a test that was mistakenly left disabled

---

tornado/ioloop.py
tornado/iostream.py
tornado/test/concurrent_test.py
tornado/test/httpclient_test.py
tornado/test/httpserver_test.py
tornado/test/iostream_test.py
tornado/test/process_test.py
tornado/test/simple_httpclient_test.py
tornado/websocket.py

Future-based interfaces will be mandatory in 6.0 for everything but set_close_callback. This branch also includes a significant refactoring of the websocket implementation to use coroutines instead of callbacks.

iostream: Deprecate callback-based interfaces

---

tornado/websocket.py

It is usefull if we need to add some custom handlers for all unexpected exceptions.
For example, in sentry project:
https://github.com/getsentry/raven-python/issues/980

Use `log_exception` method in WebSocketProtocol instead of custom logging

---

tornado/auth.py
tornado/concurrent.py
tornado/http1connection.py
tornado/httputil.py
tornado/platform/twisted.py
tornado/simple_httpclient.py
tornado/stack_context.py
tornado/test/auth_test.py
tornado/test/concurrent_test.py
tornado/test/curl_httpclient_test.py
tornado/test/gen_test.py
tornado/test/httpclient_test.py
tornado/test/httpserver_test.py
tornado/test/ioloop_test.py
tornado/test/netutil_test.py
tornado/test/simple_httpclient_test.py
tornado/test/stack_context_test.py
tornado/test/testing_test.py
tornado/test/web_test.py
tornado/testing.py
tornado/web.py
tornado/websocket.py

This is the last planned round of deprecations for 5.1. `tornado.web.asynchronous`, the whole `stack_context` module, the callback argument to `RequestHandler.flush` and `TornadoReactor` are all going away. `AsyncTestCase.stop` and `wait` are doc-deprecated but won't be removed.

Deprecate web.asynchronous, stack_context, and more

---

tornado/test/wsgi_test.py
tornado/wsgi.py

Document workaround for asyncio on multithreaded WSGI containers.
Fixes #2371

wsgi: Deprecate WSGIAdapter and WSGIApplication

---

.travis.yml
docs/faq.rst
docs/guide/async.rst
docs/guide/coroutines.rst
docs/guide/intro.rst
docs/guide/security.rst
docs/guide/structure.rst
docs/index.rst
docs/releases.rst
docs/releases/v5.1.0.rst
docs/web.rst
tornado/auth.py
tornado/concurrent.py
tornado/gen.py
tornado/httpclient.py
tornado/ioloop.py
tornado/iostream.py
tornado/locks.py
tornado/queues.py
tornado/tcpserver.py
tornado/test/concurrent_test.py
tornado/test/gen_test.py
tornado/testing.py
tornado/web.py
tox.ini

Update examples to modern interfaces.
Fully deprecate concurrent.return_future.

docs: Start release notes for 5.1

---

tornado/web.py

update set_cookie docstring to explain what expires will accept and behave properly, without having to go track down httputil.format_timestamp, which is not exposed in the docs(that I could find).

add expires docs to set_cookie.

---

tornado/test/websocket_test.py
tornado/websocket.py

Protects against memory exhaustion DoS attacks.

websocket: Limit post-decompression size of received messages

---

tornado/iostream.py
tornado/netutil.py

iostream,netutil: Ignore ENOPROTOOPT errors from SO_REUSEADDR or SO_ERROR

---

tornado/curl_httpclient.py
tornado/httputil.py
tornado/simple_httpclient.py
tornado/test/curl_httpclient_test.py
tornado/test/httpclient_test.py

httpclient: Support non-ascii characters in usernames and passwords

---

tornado/httputil.py
tornado/test/httputil_test.py

The encoding defined in RFC 2231/5987 is used by some HTTP clients (notably `requests`) when uploading a file with a non-ascii name. RFC 7578 disallows this encoding, but its predecessor RFC 2388 is ambiguous and the related RFC 6266 uses this encoding for a closely related purpose. (more details in #1898).
We had two PRs open to address this issue, #869 and #1898. This PR is based on #869 because it was the closest to working.

httputil: Support non-ascii filenames in multipart uploads

---

setup.py
tornado/options.py
tornado/test/options_test.py
tornado/test/options_test_types.cfg
tornado/test/options_test_types_str.cfg

Currently, Tornado raise an error when we use types option in configuration file such as 
options.define('datetime', type=datetime.datetime)

Update options to have same behavior from config file or command line

---

tornado/curl_httpclient.py
tornado/httpclient.py
tornado/simple_httpclient.py
tornado/test/httpclient_test.py

The HTTPResponse.request_time attribute is now consistent between curl
and simple HTTP clients (it excludes queue time in both cases). Added
a start_time attribute which can be used to see when the network
processing started.
Replaces #1032

httpclient: Improve HTTPResonse time info

---

tornado/test/httpserver_test.py
tornado/test/iostream_test.py
tornado/test/simple_httpclient_test.py
tornado/test/testing_test.py
tornado/test/web_test.py

Now the only tests using ignore_deprecation are the ones actually
testing deprecated interfaces, so the tests can be removed in 6.0.

test: Convert more tests to non-deprecated interfaces

---

tornado/simple_httpclient.py

1. http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.3
According to the spec, the temporary URI may not be specified when the request method was HEAD.
**while check _should_follow_redirect(), doesn't verify whether location is specified.**
https://github.com/tornadoweb/tornado/blob/9bb6463c07b11c6f58ee52fb59bb97ba9217c652/tornado/simple_httpclient.py#L493-L496
2.  **AsyncHTTPClient always use GET method on following redirects**：
https://github.com/tornadoweb/tornado/blob/9bb6463c07b11c6f58ee52fb59bb97ba9217c652/tornado/simple_httpclient.py#L517-L518
**but while use CURL with HEAD method, CURL will also use HEAD method on following redirects:**
```
* Hostname was NOT found in DNS cache
*   Trying 172.18.231.164...
* Connected to 172.18.231.164 (172.18.231.164) port 9999 (#0)
> …
```

_HTTPConnection: check location on _should_follow_redirect() and retain safe request when following redirects

---

demos/websocket/templates/index.html

The **websocket** demo is useful for new newcomers. 
But is has a bug as #2438 said: after send message, not clear input and focus on it!
@bdarnell, may be it too trivial?

fix issue #2438: clear input in demo projects

---

docs/guide/coroutines.rst

"coroutines has" -> "coroutines have"

Fix a grammar mistake in the user guide

---

tornado/http1connection.py
tornado/test/web_test.py

This bug exists in Tornado 5.1 and 6.0.
1. In RequestHandler.finish(), RequestHandler.flush() method will be called， the `future` returned by flush() will be finish()'s returned value.
https://github.com/tornadoweb/tornado/blob/d4eb8eb4eb5cc9a6677e9116ef84ded8efba8859/tornado/web.py#L1040
2. RequestHandler.flush() then call HTTP1Connection.write_headers() .
https://github.com/tornadoweb/tornado/blob/d4eb8eb4eb5cc9a6677e9116ef84ded8efba8859/tornado/web.py#L981-L982
3. In HTTP1Connection.write_headers(), we can know the `future` returned by finish() is exactly the `http1connection`'s ` _write_future`. **And the `_pending_write` future is already finished, but the callback `_on_write_complete` will be handled in the next iteration of `ioloop`.** …

fix issue #2448: RequestHandler.finish() future not resolving

---

demos/blog/blog.py

Blog demo has a bug as #2455 said.
The BaseHandler.query() method always returns a list. So we should access items through subscripts.

fix issue #2455: AttributeError: 'list' object has no attribute 'slug'

---

.travis.yml
setup.cfg
tornado/autoreload.py
tornado/escape.py
tornado/httputil.py
tornado/ioloop.py
tornado/iostream.py
tornado/log.py
tornado/platform/asyncio.py
tornado/platform/windows.py
tornado/routing.py
tornado/test/httpclient_test.py
tornado/test/routing_test.py
tornado/test/twisted_test.py
tornado/test/util.py
tornado/test/web_test.py
tornado/test/websocket_test.py
tornado/util.py
tox.ini

Now that we're no longer working in the superposition of python 2 and 3 (and we have py3 annotation syntax, although not 3.6 variable annotations), type annotations are a lot simpler. Add annotations to the lowest-level modules and enforce type checks in CI. 
Note that this doesn't yet provide much type-safety; it only typechecks the internals of these methods. Since other files don't have type annotations, they are ignored even when types could be inferred for calls to typed methods (there's an option for this but enabling it currently triggers a lot of warnings).

Add/update mypy annotations for util, httputil, escape

---

tornado/ioloop.py

fixes #2471
Uses `tornado.gen.convert_yielded` to convert the `handle_connection` coroutine into a future and schedules it in the event loop.

Fix IOLoop doc example code

---

setup.py

I'm not sure whether this matters, but setup.py warns about it.

setup: Fix minor typo in version number

---

tornado/platform/asyncio.py
tornado/test/httpclient_test.py

Fixes #2463
This reduces the overhead of add_callback when called on the same thread
as the event loop.  This uses asyncio's call_soon rather than
call_soon_threadsafe.

Add thread identity check to add_callback

---

tornado/iostream.py

This error is possible for some connections that don't follow through
with the TLS handshake.
Fixes #2504

iostream: Add errno 0 to the list of silent errors in TLS handshakes

---

tornado/http1connection.py
tornado/httpserver.py
tornado/locks.py
tornado/netutil.py
tornado/simple_httpclient.py
tornado/tcpclient.py
tornado/test/httpserver_test.py
tornado/test/simple_httpclient_test.py
tornado/test/web_test.py
tornado/web.py
tornado/websocket.py

This improves performance by avoiding the creation of a separate `Runner` object for each coroutine call. Now there is one runner for the connection and one for each request. 
Some rough numbers from a "hello world" HTTPServer benchmark on a 24-cpu VM:
4.5.3: 35.7k qps
5.1.1: 33.2k qps
master prior to this change: 35.7k qps
with this change: 37.2k qps
this change + uvloop: 39.6k qps
The websocket module was not updated yet because it needs a little more refactoring to continue to support clean shutdown in tests.

*: Convert most non-test coroutines to native

---

tornado/test/web_test.py
tornado/web.py

Fix issue #2521 and another similar one:
While the range end is less than start, a HTTPOutputError will also be raised.
I did the same test under `Nginx`. It served the full file but the status code is **206** with a **Content-Range** header.
```
$ curl http://localhost:8881 -s -I -H "Range: bytes=-10000000000"
HTTP/1.1 206 Partial Content
Server: nginx/1.15.5
Date: Tue, 30 Oct 2018 14:40:27 GMT
Content-Type: text/html
Content-Length: 612
Last-Modified: Tue, 02 Oct 2018 15:13:52 GMT
Connection: keep-alive
ETag: "5bb38b30-264"
Content-Range: bytes 0-611/612
```
I've also tested some other web frameworks, some of which return **416** status code.
```
$ curl http://127.0.0.1:5000/static/test.txt -s -I -H "Range: bytes=-100000"
HTTP/1.0 416 REQUESTED RANGE NOT SATISFIABLE
Content-Type: …
```

Fix #2521: Serve full file when range start is negative and exceeds the total length

---

tornado/process.py
tornado/tcpserver.py

#1628 redux
Current use case: we have a memory leak we're working on fixing. In the mean time, we can allow for 0 down time and capping memory usage by periodically killing child processes and setting max_restarts very high.

allow configurable max_restarts in TCPServer.start

---

tornado/httpclient.py
tornado/simple_httpclient.py
tornado/test/httpclient_test.py

Extend support for HTTPRequest's network_interface parameter to SimpleAsyncHTTPClient. This enables binding to specific local IP and enables connecting to WebSockets via a specific IP address.
To use it you create a HTTPRequest with network_interface parameter set to local IP address to be used as source IP. websocket_connect then passes the request to SimpleAsyncHTTPClient.
Note that even though the parameter name is `network_interface`, the CurlAsyncHTTPClient may support (OS dependant) passing in interface name, resolvable hostname or IP address, while this patch only adds IP address support to SimpleAsyncHTTPClient.
As a curious side note, the curl library also supports prefixing the passed-in string with `"if!"` or `"host!"` to force parsing parameter as interface or host name …

Add support for source IP address to SimpleAsyncHTTPClient.

---

tornado/test/web_test.py
tornado/web.py

Hi,
We are adopting Tornado at work, and I started reading its internal API (which is super neat! kudos!, and pending issues to get familiar with the code.
Found #462, and thought it looked simple, so decided to try to understand where the change would occur and suggest a fix in a pull request.
First time contributing to Tornado, so feel free to point me if I forgot anything. Not sure if that's something easy to be tested? If so, if someone could point me to a similar test, I'd be happy to include one here. It worked testing locally and confirming in Firefox web developer Storage tab for the cookie info.
Thank you very much for Tornado!
Bruno

Define XSRF cookie expires_day via settings

---

.travis.yml
tornado/httpclient.py
tornado/test/httpclient_test.py

If an HTTPClient is closed from its destructor instead of an explicit
close() call, it sometimes logs an "inconsistent AsyncHTTPClient
cache" error because the weakrefs appear to get cleaned up in an
unexpected order. Relax the checks in AsyncHTTPClient.close to allow
for a missing value in the instance cache.
Fixes #2539

httpclient: Fix warning logged by sync HTTPClient destructor

---

tornado/concurrent.py
tornado/httpclient.py
tornado/iostream.py
tornado/process.py
tornado/test/httpclient_test.py

Tornado's limited support for cancellation means that errors after a
Future is cancelled could get raised (and probably logged) as
InvalidStateErrors.
This new function effectively changes the behavior to log the real
exception instead of the InvalidStateError. We log them instead of
ignoring them because it's generally not a good idea to let errors
pass silently even if they're after the point that no one is listening
for them (this is consistent with the way gen.multi() handles multiple
errors, for example).
Fixes #2540

concurrent: Add future_set_exception_unless_cancelled

---

tornado/http1connection.py
tornado/test/web_test.py

I'm so sorry that the PR #2449 was incomplete, it omited consideration of another
branch of the `RequestHandler.flush()`. In short, the future returned by
`RequestHandler.finish()` may also be the return value of
`HTTP1Connection.write()`. So we should make the same change to
`HTTP1Connection.write()`.
Fix #2448.

Use 'future_add_done_callback' to add callback.

---

docs/conda.yml
docs/conf.py
docs/requirements.txt
maint/requirements.in
maint/requirements.txt
readthedocs.yml

Upgrade to sphinx 1.8.
Build with python 3.7 on readthedocs.org.
Remove year from copyright variable.

docs: Minor updates

---

tornado/queues.py

Tornado's interpretation of the timeout argument differs from the
stdlib's queue.
Fixes #2370

queues: Add a note to Queue.get about difference from stdlib

---

tornado/http1connection.py
tornado/simple_httpclient.py
tornado/test/httpclient_test.py

This is a second attempt at #2409, which was reverted in #2439 because it was merged too close to 5.1's release. This should have a test added (to verify that the behavior is consistent between simple and curl clients) before it is merged.

httpclient: Validate redirect location header and method

---

tornado/test/websocket_test.py
tornado/websocket.py

Previously if open() was a coroutine and raised an error, the
connection would be left open.
Fixes #2570

websocket: Catch errors in async open() correctly

---

tornado/httputil.py

Applications that use content-encoding on requests were logging a
warning every time.
Fixes #2578

httputil: Remove a noisy log line

---

docs/faq.rst
docs/guide/coroutines.rst
docs/guide/intro.rst
docs/guide/running.rst
docs/guide/structure.rst
docs/guide/templates.rst
docs/index.rst
docs/web.rst
tornado/auth.py
tornado/concurrent.py
tornado/httpclient.py
tornado/ioloop.py
tornado/iostream.py
tornado/netutil.py
tornado/testing.py
tornado/util.py
tornado/web.py
tornado/websocket.py

I've recently started development work using Tornado for the first time & naturally have been examining the documentation in detail to understand the internals.
I'm pedantic so along the way picked up on some (very) small issues e.g. in formatting (mainly missing capitalisation & plain text instances which would be more appropriate & readable as inline literals) which I noted down within an open branch.
I thought I might as well open this PR should you be happy to accept various such tweaks, or indeed a subset of them as I am happy to remove any changes that are unwanted. However if this seems excessive I am happy to close the PR.

docs: assorted minor e.g. formatting improvements

---

tornado/ioloop.py
tornado/test/iostream_test.py

Asyncio Futures always schedule their callbacks on a future iteration
of the IOLoop, so routing the callbacks through IOLoop.add_callback
again was redundant and causing unnecessary delays in callback
execution.

ioloop: Micro-optimize IOLoop.add_future

---

tornado/test/websocket_test.py
tornado/websocket.py

Previously if open() was a coroutine and raised an error, the
connection would be left open.
Fixes #2570
backport of dc354c57adac to 5.1
Since the cherry-pick has conflicts and needed adapting to a pre-async-await world, I figured I would do the backport, in the hope it makes maintenance a bit easier.
cc @heybuddy

websocket: Catch errors in async open() correctly (5.1 backport)

---

.travis.yml
tornado/concurrent.py
tornado/gen.py
tornado/http1connection.py
tornado/httpclient.py
tornado/ioloop.py
tornado/iostream.py
tornado/locks.py
tornado/simple_httpclient.py
tornado/testing.py
tornado/web.py
tornado/websocket.py
tornado/wsgi.py

The "provisional" typing module in 3.5.2 is kind of broken/incomplete
so we need to use more forward references to avoid confusing it. The
significance of this version in particular is that it was the one
included in ubuntu 16.04.
Fixes #2604

Fix importability on python 3.5.2

---

.travis.yml

Travis-CI Trusty Container-based environment was available
between July, 2017 and December, 2018.
https://docs.travis-ci.com/user/reference/overview/#deprecated-virtualization-environments

travis-ci tests: always use dist xenial

---

tornado/platform/twisted.py

Let the documentation in `TwistedResolver` specify the minimum version since the module docstring was out of date.

Remove twisted version comment in module docstring

---

tornado/test/websocket_test.py
tornado/websocket.py

This method was untested and broken in 6.0.0.
Fixes #2611

websocket: Fix set_nodelay

---

tornado/httpclient.py

In tornado 5, HTTPResponse.body would return None if there was no body
buffer (which included errors like timeouts and socket errors, but not
HTTP errors like 404). In tornado 6 this was changed to never return
None (to make it easier to work with type annotations) and raise an
error instead. This turned out to be disruptive, so change it back to
returning a value without raising (but now it's an empty byte string
instead of None).
Fixes #2626

httpclient: HTTPResponse.body returns empty string instead of raising

---

maint/benchmark/parsing_benchmark.py
tornado/httputil.py

Replace `_CRLF_RE.split(headers)` with a simple `headers.split('\n')` with an additional check for '\r' in each line.
I've benchmarked this change on Tornado 4.5 with the latest pypy2.7 (that's what we have in production now): the splitting itself is ~20x faster, and the whole headers parsing is ~4-5x faster.
I'm opening this as a draft PR to discuss the feasibility of this change; if you like the general idea, I'm willing to add any necessary changes.

Speedup headers parsing

---

tornado/platform/twisted.py

This function had more usage than I was aware of and we can preserve
the old behavior by making it an alias for asyncioreactor.install.
Fixes #2636

twisted: Restore the install() function

---

.travis.yml
docs/conf.py
docs/requirements.txt

Two ways to do this: downgrade sphinx, or get rid of sphinxcontrib-asyncio. I'll push up commits for both.
-----
example docs build error:
```
.../tornado/tornado/auth.py:docstring of tornado.auth.OpenIdMixin.get_authenticated_user:1:Error in "py:comethod" directive:
unknown option: "async".
.. py:comethod:: OpenIdMixin.get_authenticated_user(http_client: tornado.httpclient.AsyncHTTPClient = None) -> Dict[str, Any]
:module: tornado.auth
:async:
Fetches the authenticated user data upon redirect.
...
```
where does that stuff come from? let's see:
```
$ ag comethod
venv/lib/python3.6/site-packages/sphinxcontrib/asyncio.py
100:class CoMethodDocumenter(MethodDocumenter):
104:    objtype = "comethod"
125:        self.directivetype = "comethod"
149:    app.add_directive_to_domain('py', …
```

docs: conflict between sphinx-2.1, sphinxcontrib-asyncio

---

tornado/curl_httpclient.py
tornado/test/httpclient_test.py
tornado/test/simple_httpclient_test.py

by setting None (NULL) instead of "none" for ENCODING
reported by Andrey Oparin <andrey@edsd.com> in https://github.com/tornadoweb/tornado/issues/2065#issuecomment-500358399 cc @andrey-oparin
~~I haven't tested this myself, I'll look into making a unit test for this soon ...~~

curl_httpclient: fix disabled decompress_response

---

docs/httpserver.rst
docs/web.rst
setup.cfg
tornado/auth.py
tornado/curl_httpclient.py
tornado/http1connection.py
tornado/httpclient.py
tornado/httpserver.py
tornado/httputil.py
tornado/ioloop.py
tornado/iostream.py
tornado/locale.py
tornado/locks.py
tornado/log.py
tornado/netutil.py
tornado/options.py
tornado/process.py
tornado/queues.py
tornado/routing.py
tornado/simple_httpclient.py
tornado/tcpclient.py
tornado/tcpserver.py
tornado/template.py
tornado/testing.py
tornado/util.py
tornado/web.py
tornado/websocket.py

The runtime already allows and deal with `None` values here. Adding `Optional` improves the type checking and (since this is public API) allows users to run their type checker with strict-optional.

Add Optional for types on expires/expires_days

---

tornado/gen.py

Hello!
I'm not very familiar with Tornado, but I'm investigating the failure on Python 3.8 (#2677).
From commit a237a995a1d54ad6e07c1ecdf5103ff8f45073b5, it seems that CancelledError should also be ignored in `tornado.gen.with_timeout`'s `error_callback`. Is that right?
This fixed tests on Python 3.8.0b1 for me.

gen.with_timeout: Don't log CancelledError after timeout

---

.travis.yml
tornado/gen.py
tornado/locks.py

python/cpython#13528 broke us in two ways: asyncio.CancelledError is
no longer an alias for concurrent.futures.CancelledError and it's now
a BaseException.
Fixes #2677
Closes #2681
cc @1st1

gen: Adapt to py38 CancelledError changes

---

tornado/ioloop.py
tornado/iostream.py
tornado/netutil.py
tornado/process.py
tornado/test/iostream_test.py
tornado/test/tcpclient_test.py

This happens in docker with default configurations and is generally
harmless.
Fixes #2274
The first commit turns out to be unrelated; I thought it would streamline the second commit but there's no exception type for EADDRNOTAVAIL. With the third commit, the tests run cleanly in docker.

netutil: Ignore EADDRNOTAVAIL when binding to localhost ipv6

---

docs/index.rst

docs: Add notice about WindowsSelectorEventLoop on py38

---

tornado/web.py

Now that the `callback` argument has been removed, the docstring for the method should not be all about it.
This could be replaced with some doc about how the returned future works, though really there shouldn't be concurrent writers.

Strip documentation about removed argument

---

tornado/template.py

The documentation indicates setting `autoescape=None` will disable autoescaping but the previous type hinting did not allow a value of `None`.

Mark Template autoescape kwarg as Optional

---

docs/guide/security.rst

The blog example was updated a while ago to use Postgres but the user's guide still says it's using MySQL for storage.

Update database backend reference

---

tornado/test/iostream_test.py

This test started failing on windows CI with an upgrade to python
3.7.4 (which bundles a newer version of openssl). Disable tls 1.3 for
now.
Possibly related to #2536

test: Disable TLS 1.3 in one test

---

tornado/escape.py
tornado/httputil.py
tornado/test/httpserver_test.py
tornado/test/httputil_test.py
tornado/test/simple_httpclient_test.py
tornado/test/web_test.py

support x-www-form-urlencoded body with values consisting of
encoded bytes which are not url-encoded into ascii
(as long as there is no ambiguous `&` or `%` or `=`)
it seems other web frameworks often support this
inspired by #2733 and #2572

parse_body_arguments: allow incomplete url-escaping

---

tornado/http1connection.py
tornado/test/httpserver_test.py

Hi, Tornado send extra data `0\r\n\r\n` at HEAD response with Transfer-Encoding: Chunked.
```zsh
➜  ~ telnet localhost 8888
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
HEAD / HTTP/1.1
HTTP/1.1 200 OK
Server: TornadoServer/6.1.dev1
Content-Type: text/html; charset=UTF-8
Date: Sun, 08 Sep 2019 03:19:09 GMT
Transfer-Encoding: chunked
0
```

Fix extra data sending at HEAD response with Transfer-Encoding: Chunked

---

tornado/test/httpclient_test.py
tornado/test/web_test.py
tornado/web.py

This function is called on more than just 304 responses; it’s important to permit the Allow header on 204 responses.  Also, the relevant RFCs have changed significantly.
Fixes #2726.

Clear fewer headers on 1xx/204/304 responses

---

.travis.yml
tox.ini

A new release of black changed the way some of our files are formatted,
so use a fixed version in CI.

ci: Pin version of black

---

demos/webspider/webspider.py

Updates #2765
The lint failure wasn't entirely caused by the black version change.

demos: Fix lint in webspider demo

---

.travis.yml
tox.ini

Reduce tox matrix to one env per python version, with two extra builds
for lint and docs. Delegate to tox from travis-ci.

build: Revamp test/CI configuration

---

.travis.yml

Twisted doesn't install with the version of pip bundled with python 3.5.2.
(Error message about platform_system)

ci: Don't run the full test suite on python 3.5.2

---

tornado/test/web_test.py
tornado/web.py

Addresses #2776.
Some quick testing shows that SHA1 is somewhat faster than MD5 on
newer versions of Python:
```python
import hashlib
import secrets
data = secrets.token_bytes(1024 * 10000)
```
Using Jupyter's `%%timeit` magic:
```
%%timeit
hasher = hashlib.md5()
hasher.update(data)
hasher.hexdigest()
```
Example output: `12.5 ms ± 345 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)`
```
%%timeit
hasher = hashlib.sha1()
hasher.update(data)
hasher.hexdigest()
```
Example output: `8.94 ms ± 306 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)`

Update hashing algorithm in StaticFileHandler

---

.gitattributes
appveyor.yml
tornado/platform/asyncio.py
tornado/test/__init__.py
tornado/test/httpserver_test.py
tornado/test/iostream_test.py
tornado/test/netutil_test.py
tornado/test/simple_httpclient_test.py
tornado/test/twisted_test.py
tornado/testing.py

Fix various issues with tests on windows (and when running tests outside of runtests.py):
- Add gitattributes file to control line endings
- Force the use of the selector event loop in tests (this may be replaced by a more general solution in the future, but for now this gets the tests working)
- Skip a few tests and add some attribute guards
- Add a level argument to ExpectLog so it doesn't rely on logging configuration from runtests.py

Improve tests on windows

---

tornado/iostream.py
tornado/test/iostream_test.py

Includes code from #2719 and tests from #2720. 
Fixes two bugs related to interactions between reads and closes:
- Reads which started before the close can now complete from data read into the buffer before the stream closed.
- Reads which start after the close can also use buffered data instead of immediately raising an error.
Fixing the latter issue narrowed the scope of the change introduced in #2670, so we should watch for a recurrence of #2651. We haven't been able to construct good test cases for #2651 or the second issue fixed here; the timing required is subtle (although we have non-unittest reproductions). 
Closes #2717
Closes #2719 
Closes #2720

iostream: Resolve pending reads on stream close

---

setup.py

I think this is okay as CI is running against Python 3.8
https://github.com/tornadoweb/tornado/blob/f7d94d0e8a57f51ffc0aac5d55ed7bf9f9936b4d/.travis.yml#L28-L29

Add Python 3.8 clasifier to setup.py

---

.travis.yml

Looks like some server-side change broke our build. 
Cherry-picked from @minrk in https://github.com/bdarnell/tornado/pull/2/commits

ci: Fix travis.yml

---

.travis.yml
appveyor.yml
docs/releases.rst
docs/releases/v6.0.4.rst
setup.py
tornado/__init__.py
tornado/httputil.py
tornado/iostream.py
tornado/platform/asyncio.py
tornado/tcpclient.py
tornado/test/__init__.py
tornado/test/iostream_test.py
tornado/web.py

Includes:
- #2805 to fix a regression in iostream in 6.0.x
- #2812 setup.py classifier for python 3.8
- #2818 fix CI config
- #2799 python 3.8 on windows ci
- #2725 disable tls 1.3 in one test

Backports for release 6.0.4

---

tornado/iostream.py

The SSL module has CertificateErrors which are not thrown by the ssl module, and so also need to be handled.
Fixes: tornadoweb/tornado#2689

SSLIOStream: Handle CertificateErrors like other errors

---

tornado/routing.py

This removes an extra parenthesis in the nested routing documentation example to allow the example to work.

Fix syntax error in nested routing example

---

docs/conda.yml
readthedocs.yml

This reverts commit e7e31e5642ae56da3f768d9829036eab99f0c988.
We were using conda to get access to python 3.7 before rtd supported
it in their regular builds, but this led to problems pinning a
specific version of sphinx. See
https://github.com/readthedocs/readthedocs.org/issues/6870

Revert "docs: Use python 3.7 via conda for readthedocs builds"

---

tornado/http1connection.py
tornado/web.py

In my last PR (https://github.com/tornadoweb/tornado/pull/2859), the travis pipeline failed. It is because in the new released `flake8` version, the E741 detection was improved inside comprehensions. This PR should fix both cases.

fix new E741 detected cases

---

.travis.yml
tornado/test/process_test.py
tox.ini

Not sure why this has recently started happening in some environments,
but killing a process too soon causes the wrong exit status in some
python builds on macOS.

test: Add a sleep to deflake a test

---

tornado/web.py

The `max_age_days` and `expires_days` parameters are currently defined to be `int`, but they should be `float`, per the discussion here:
https://stackoverflow.com/questions/30526438/tornado-create-a-secure-cookie-with-expiry-time-less-than-1-day
I can also empirically state that float parameters work, as they are being used in my tornado-based app.
`float` is the correct type for these parameters, per:
https://www.python.org/dev/peps/pep-0484/#the-numeric-tower
> when an argument is annotated as having type float, an argument of type int is acceptable

fix types for max_age_days and expires_days parameters

---

tornado/template.py

Makes the sentence a little less confusing.

Clarify instructions for escaping special character sequences

---

tornado/httpclient.py

Only the `body` and `body_producer` arguments didn't have type info in the documentation page (see https://www.tornadoweb.org/en/stable/httpclient.html#request-objects )
Thanks for the great project!

Standardize type documentation for HTTPRequest init

---

tornado/template.py

Originally from #2831, which went to the wrong branch.

template: Clarify docs on escaping

---

tornado/auth.py

From tornado 6.0 OAuth2Mixin->authorize_redirect is an ordinary synchronous function.
Example returns error when await is used:
```Uncaught exception GET /auth/google (127.0.0.1)
HTTPServerRequest(protocol='http', host='example.com', method='GET', uri='/auth/google', version='HTTP/1.0', remote_ip='127.0.0.1')
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1699, in _execute
result = await result
File "app.py", line 84, in get
extra_params = {"approval_prompt": "auto"}
TypeError: object NoneType can't be used in 'await' expression
```

Fix Google OAuth example

---

tornado/test/process_test.py

The 1s timeout used here has become flaky with the introduction of a
sleep (before the timeout even starts).

test: Use default timeouts in sigchild test

---

tornado/auth.py

Continuation of #2811
The oauth2 version of authorize_redirect is no longer a coroutine, so
don't use await in example code. The oauth1 version is still a
coroutine, but one twitter example was incorrectly calling it with
yield instead of await.

auth: Fix example code

---

tornado/test/testing_test.py

This test was flaky on appveyor. Also expand comments about what
exactly the test is doing.

test: Use larger time values in testing_test

---

tornado/concurrent.py

Hi,
The `callback` argument was removed in [this commit](https://github.com/tornadoweb/tornado/commit/09267029aaf188deee2bc6b39a91b0fc42814466). So I think the text at the top of the function documentation can be updated too.
Thanks
Bruno

Remove text about callback (removed) in run_on_executor

---

tornado/curl_httpclient.py

This restores curl's default behaviour: use environment variables.
This option was set to "" to disable proxy in
905a215a286041c986005859c378c0445c127cbb but curl uses environment
variables by default.
pycurl has supported this on master with https://github.com/pycurl/pycurl/pull/640.

curl_httpclient: set CURLOPT_PROXY to NULL if pycurl supports it

---

docs/requirements.txt

The just-released version 0.3.0 is incompatible with our older pinned
version of sphinx.

docs: Pin version of sphinxcontrib-asyncio

---

tornado/gen.py

`@gen.coroutine` deco allows non-yielding functions, so I reflected that in the type hint.
Requires usage of `@typing.overload` due to https://github.com/python/mypy/issues/9435

Allow non-yielding functions in `tornado.gen.coroutine`'s type hint

---

tornado/_locale_data.py
tornado/locale.py
tornado/test/curl_httpclient_test.py
tornado/test/httpclient_test.py
tornado/test/httputil_test.py
tornado/test/options_test.py
tornado/test/util_test.py

On Python 3, utf-8 is the default python source code encoding so, the coding cookies on files that specify utf-8 are not needed anymore. There are no coding cookies in the package after these changes are made.
Ref : https://docs.python.org/3/tutorial/interpreter.html#source-code-encoding

Remove utf-8 coding cookies in source files

---

docs/index.rst

* Updated http links to the https versions when possible.
* Updated links to Google Groups to match their new URL format.
* Updated links to other projects to match their new locations.
* And finally, updated link to FriendFeed to go to the Wikipedia page, because friendfeed.com is just a redirect to facebook.com now :-( :-(

Update links on home page

---

tornado/simple_httpclient.py
tornado/test/httpclient_test.py

tests: httpclient may turn all methods into GET for 303 redirect

---

tornado/test/websocket_test.py
tornado/websocket.py

cleanup of #2876 
partial fix for #2405 
It seems like `request.follow_redirects = False` might make more sense in `WebSocketClientConnection.__init__()` next to all the request url and header modification, I could easily move it there if you agree ...

websocket: set follow_redirects to False

---

tornado/httpclient.py
tornado/simple_httpclient.py
tornado/test/httpclient_test.py

Using a connect_timeout or request_timeout of 0 was effectively
invalid for simple_httpclient: it would skip the actual request
entirely (because the bulk of the logic was inside "if timeout:").
This was not checked for or raised as an error, it just behaved
unexpectedly.
Change simple_httpclient to always assert these timeouts are not None
and to support the 0 value similar to curl (where request_timeout=0
means no timeout, and connect_timeout=0 means curl default 300 seconds
which is very very long for a tcp connection).
related: https://github.com/tornadoweb/tornado/issues/2742
most of the diff showed is a re-indent after "if timeout:", you can conveniently view only non-whitespace changes at: https://github.com/tornadoweb/tornado/pull/2919/files?w=1

simple_httpclient: handle connect_timeout or request_timeout of 0

---

tornado/http1connection.py
tornado/test/httpclient_test.py

#2875 plus a unit test
The trigger is indeed just a single extra null byte at the end:
```
$ ls -l bad-response-hangs-tornado.gz 
-rw-rw-rw-@ 1 pierce  staff  31792 Sep 25 00:56 bad-response-hangs-tornado.gz
$ cat bad-response-hangs-tornado.gz | gunzip -c | wc -c
gunzip: (stdin): trailing garbage ignored
149051
$ head -c 31791 bad-response-hangs-tornado.gz | gunzip -c | wc -c
149051
$ head -c 31790 bad-response-hangs-tornado.gz | gunzip -c | wc -c
gunzip: truncated input
149051
$ hexdump -C bad-response-hangs-tornado.gz | tail -n2
00007c20  45 54 a6 3b 4a ff 3f 84  e2 cc 59 3b 46 02 00 00  |ET.;J.?...Y;F...|
00007c30
```
But it wasn't trivially easy to find a response body that triggers the bug - a single gzipped "Hello World", or just 50 times that, doesn't do it. So I tried generating …

simple_httpclient: fix infinite loop hang with invalid gzip data

---

.travis.yml
tornado/test/netutil_test.py

- Add osx and windows builds on travis
- Stop running -full test suites on every python version on arm64
- Use cibuildwheel to build for all python versions in one job per
platform
- Bring a single test configuration and linters up to a first "quick"
stage before starting the whole matrix
- Push the resulting wheels (and sdist) to pypi on tag builds

test: Refactor CI configuration

---

tornado/gen.py
tornado/test/gen_test.py

The asyncio event loop provides enough contextvars support out of the
box for basic contextvars functionality to work in tornado coroutines,
but not `contextvars.reset`. Prior to this change, each yield created
a new "level" of context, when an entire coroutine should be on the
same level. This is necessary for the reset method to work.
Fixes #2731

gen: Expliclty track contextvars, fixing contextvars.reset

---

appveyor.yml
tornado/platform/asyncio.py
tornado/test/httpclient_test.py

Python 3.9 changed the behavior of ThreadPoolExecutor at interpreter
shutdown (after the already-tricky import-order issues around
atexit hooks). Avoid these issues by managing the thread by hand.

asyncio: Manage our own thread instead of an executor

---

.travis.yml
setup.py
tox.ini

Start testing this with the 3.9 pre-releases.

ci,setup: Add python 3.9 to tox, cibuildwheel and setup.py

---

tornado/locale.py

Prevents errors logged at startup when the translation directory is shared with other projects.
Updates #2956 to fix formatting for CI.
Fixes #2954 
Closes #2956

locale: Only try to load locales that exist

---

tornado/gen.py

When used with `asyncio.Future`s, `WaitIterator` may skip indices in some cases. This is caused by multiple `_return_result` calls after another, without having the `chain_future` call finish in between. This is fixed here by not hanging on to the `_running_future` anymore, which forces subsequent `_return_result` calls to add to `_finished`, instead of causing the previous result to be silently dropped.
I couldn't yet figure out a minimal test case, I only got consistent failures as part of a larger program (via [distributed.utils.All](https://github.com/dask/distributed/blob/6fa9b1849a2ed43d123a9ae6221354cb420ce333/distributed/utils.py#L212)) - any help is appreciated!
Fixes #2034

WaitIterator: don't re-use _running_future

---

tornado/netutil.py

There is a small typo in tornado/netutil.py.
Should read `authenticate` rather than `authentiate`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, authentiate -> authenticate

---

demos/blog/blog.py

change `u"Tornado Blog"` to `"Tornado Blog"`

should use python3 unicode in 'blog' demo #2977

---

tornado/iostream.py

This PR avoids an 2GB read (at once) limitation for `iostream.SSLIOStream`, by silently capping read attempts to 1GB.
Normal operation (using the internal buffers) or `read_into` attempts with `len` < 1GB will not be affected by this change at all.
This issue can be encountered when using `read_into` e.g. during [`dask`'s data transfers](https://github.com/dask/distributed/blob/master/distributed/comm/tcp.py#L196) (with enabled TLS).
The underlying cause lies in Python's [`ssl.SSLSocket.read`](https://docs.python.org/3/library/ssl.html#ssl.SSLSocket.read), which has a 2GB limitation.
The limitation is caused by an [`int`-type `len`gth  argument](https://github.com/python/cpython/blob/master/Modules/_ssl.c#L2520).
This seems to be intended, albeit undocumented, behavior since an [related …

Avoid 2GB read limitation on SSLIOStream

---

tornado/testing.py

Specify custom address by "address" keyword when use `tornado.testing.bind_unused_port` function.

Add 'address' keyword control binded address #2969

---

demos/blog/docker-compose.yml

This is a new approach to avoid Docker image python app initialize first, causing a failure in connection between python app and postgres.
I found this solution on a post in [stackoverflow](https://stackoverflow.com/questions/35069027/docker-wait-for-postgresql-to-be-running)
Signed-off-by: Emory Freitas <emory.rvf@gmail.com>

Update docker composer file version and wait for postgres #2784

---

tornado/websocket.py

It was no longer used and always set to None.

Remove WebSocketHandler.stream.

---

tornado/iostream.py
tornado/test/iostream_test.py

This PR implements support of `memoryviews` with an item size greater than 1 byte.
Currently, Tornado uses `len(x)` to retrieve the number of bytes of `x`, which works fine when `x` is `bytes` or a `memoryview` with an item size of 1. However, with an item size greater than 1 we cannot assume that `len(x) == x.nbytes`.

BaseIOStream.write(): support typed memoryviews

---

tornado/ioloop.py
tornado/test/ioloop_test.py

Instead of requiring callers to convert their desired callback time to milliseconds, this change allows for passing in `timedelta`s:
```python
from datetime import timedelta
from tornado.ioloop import PeriodicCallback
task = PeriodicCallback(lambda: print("ping"), timedelta(minutes=1, seconds=23))
task.start()
```

Accept timedelta objects in PeriodicCallback

---

tornado/netutil.py
tornado/test/netutil_test.py

Calling `socket.getaddrinfo` with a potential hostname attempts to
encode the "hostname" with the `idna` encoding.  Per RFC, each part of
the hostname cannot be longer than 63 characters; and `getaddrinfo`
enforces this by raising a UnicodeError if the length is too long.
Catch these UnicodeErrors and return false for too-long names, rather
than raising an exception.

is_valid_ip: Do not raise exceptions on too-long input.

---

tornado/ioloop.py
tornado/platform/asyncio.py
tornado/test/ioloop_test.py

#2832 plus some tests
-------
EDIT: nevermind, figured out how to avoid this
ORIGINAL:
I can't quite figure out how to quiet this error log:
```
[E 200927 21:24:05 ioloop:910] Exception in callback <function TestPeriodicCallbackAsync.test_periodic_coro.<locals>.callback at 0x10a2a6c80>
Traceback (most recent call last):
File "/Users/pierce/scratch/tornado/tornado/ioloop.py", line 908, in _run
await val  # type: ignore
concurrent.futures._base.CancelledError
```
The usual pattern doesn't work:
```python
with ExpectLog(app_log, "Exception in callback"):
self.wait()
```
even if I extend it to:
```python
with ExpectLog(app_log, "Exception in callback"):
pc = PeriodicCallback(callback, 10)
pc.start()
self.wait()
pc.stop()
```

PeriodicCallback: support async/coroutine callback

---

.github/workflows/test.yml
docs/index.rst
pyproject.toml
setup.cfg
setup.py
tornado/ioloop.py
tornado/iostream.py
tornado/netutil.py
tornado/platform/asyncio.py
tornado/test/asyncio_test.py
tornado/test/httpclient_test.py
tornado/test/httpserver_test.py
tornado/test/ioloop_test.py
tornado/test/iostream_test.py
tornado/test/process_test.py
tornado/test/simple_httpclient_test.py
tornado/test/testing_test.py
tornado/test/twisted_test.py
tornado/test/util.py
tornado/testing.py
tox.ini

Python 3.10 deprecated a number of things we rely on.
In the future, `asyncio.get_event_loop` will become an alias for `get_running_loop`, and anything related to supporting an event loop that is "current" but not running has been deprecated. This is very disruptive for us because that has been the normal mode of operation for tornado during application setup and many testing idioms. For now we need to get the test suite passing, so we catch deprecation warnings in various places and introduce new deprecation warnings to give users better message for things that we'll have to remove. 
There are no intended changes in behavior except as it relates to deprecation warnings; applications that disable these warnings should be unaffected. In some future version of python, most tornado …

Handle deprecations in python 3.10

---

tornado/test/web_test.py
tornado/web.py

* fix optional whitespace parsing of Accept-Language header
* fix ignoring quality=0 values in Accept-Language
* disallow negative quality values in Accept-Language

Fix tornado.web.RequestHandler.get_browser_locale()

---

docs/util.rst
tornado/gen.py
tornado/ioloop.py
tornado/test/import_test.py
tornado/util.py

for more consistent catching of timeouts with other asyncio code.
should be fully backward-compatible. Docs updated as well.
closes #2800

make gen.TimeoutError asyncio.TimeoutError

---

tornado/log.py

Found with python/typeshed#6620

Handle curses.tigetstr() returning None

---

tornado/curl_httpclient.py
tornado/test/httpclient_test.py
tornado/test/import_test.py

It's not possible to contain non-ASCII values in HTTP headers using the async `pycurl` HTTP client
- OK: `tornado.httputil.HTTPHeaders()` only allows to contain unicode strings.
- OK: `tornado.escape.native_string()` would always produce a `UTF-8` decoded string - used here makes only sense for py2 compatibility
- FAIL: unicode strings are given to pycurl instead of bytes, pycurl only accepts ASCII unicode strings
Example failure:
```
from io import BytesIO
import tornado.curl_httpclient
c = tornado.curl_httpclient.CurlAsyncHTTPClient()
curl = c._curls[0]
headers = tornado.httputil.HTTPHeaders({
"Foo": "b\xe4r",
})
request = tornado.httpclient.HTTPRequest(
'http://www.example.com', follow_redirects=True, max_redirects=3,
connect_timeout=1, request_timeout=1, headers=headers
) …
```

fix[curl_httpclient]: allow HTTP header to include non-ASCII ISO8859-1 values

---

demos/file_upload/file_receiver.py
demos/file_upload/file_uploader.py
tornado/iostream.py

Parameter 'streaming' has been obsolete since a55c7fe7 in 2018-07
when `_run_read_callback()` was renamed to `_finish_read()`.
This param should be removed as well after the removal of callback
in IOStream.

Remove obsolete param 'streaming' in BaseIOStream._finish_read()

---

tornado/test/websocket_test.py
tornado/websocket.py

As doc says "If the stream is closed, raises WebSocketClosedError"
Fix #3002

Fix websocket client already closed raise error does not match

---

tornado/test/testing_test.py
tornado/testing.py

Since Python 3.2 the functools.wraps decorator adds a __wrapped__ attribute
pointing to the original callable, this allows wrapped functions to be introspected.

Add __wrapped__ attribute to _TestMethodWrapper

---

tornado/web.py

Type-hint stream_request_body so that the type of `stream_request_body(cls)` is the same as the type of `cls`.

Type-hint stream_request_body correctly

---

tornado/ioloop.py
tornado/platform/asyncio.py

clean-up some methods that were missed in
https://github.com/tornadoweb/tornado/pull/2924

ioloop: add_timeout() and call_at() take any Callable

---

docs/conf.py
tornado/web.py

Our version of sphinx isn't resolving this annotation correctly.
Introduced in #3014 because CI was broken when it was submitted.

web: Fix type annotation for docs build

---

tornado/netutil.py

`ExecutorResolver` doesn't use the `io_loop` and so just raises a deprecation warning if constructed without a running event loop

avoid acquiring IOLoop in ExecutorResolver

---

maint/scripts/test_resolvers.py
tornado/netutil.py

usually this is pretty much the same as DefaultExecutorResolver, (the stdlib event loop just uses the default executor) however some loops eg `uvloop.Loop` do implement `getaddrinfo`

 provide Resolver implementation that uses the asyncio eventloop

---

tornado/ioloop.py
tornado/platform/asyncio.py
tornado/test/asyncio_test.py

`with warnings.catch_warnings():` mutates the warnings filters for the
whole process and so is unsafe to call from multiple threads

avoid thread unsafe catch_warnings

---

tornado/ioloop.py
tornado/platform/asyncio.py

Python 3.2+ now features a logger of lastResort https://docs.python.org/3/library/logging.html#logging.lastResort and so I think _setup_logging is redundant

remove _setup_logging

---

tornado/wsgi.py

wsgiref.types is a new module in Python 3.11. Accordingly, typeshed's stubs were updated so that this module is only available from Python 3.11 onwards. But the typeshed-specific module _typeshed.wsgi (which is considered stable by typeshed) contains all the necessary definitions for all supported Python versions.

Import WSGI types from _typeshed.wsgi

---

tornado/autoreload.py

This is unnecessary since python 3.2 added a default logger of
last resort (and the two calls that precede "info" log messages
didn't do anything in the first place since basicConfig only logs
warnings and higher).
Fixes the second part of #2961

autoreload: Remove calls to logging.basicConfig

---

demos/blog/blog.py
demos/chat/chatdemo.py
demos/facebook/facebook.py
demos/file_upload/file_receiver.py
demos/file_upload/file_uploader.py
demos/helloworld/helloworld.py
demos/s3server/s3server.py
demos/tcpecho/client.py
demos/tcpecho/server.py
demos/twitter/twitterdemo.py
demos/websocket/chatdemo.py
demos/webspider/webspider.py
docs/guide/coroutines.rst
docs/guide/intro.rst
docs/guide/queues.rst
docs/guide/running.rst
docs/guide/structure.rst
docs/index.rst
tornado/httpserver.py
tornado/ioloop.py
tornado/iostream.py
tornado/locks.py
tornado/queues.py
tornado/web.py
tornado/wsgi.py

Adapt for Python 3.10 deprecation changes by using asyncio.run
instead of IOLoop.start throughout (except for TCPServer multi-process
docs).
Demos have all been changed but I haven't tested all of them.

docs,demos: Update for asyncio.run pattern

---

docs/guide/running.rst
tornado/httpserver.py
tornado/tcpserver.py
tornado/test/tcpserver_test.py

This is partially a casualty of the Python 3.10 deprecation
changes, although it's also something I've wanted to do for other
reasons, since it's been a very common source of user confusion.
Fixes #2801

tcpserver: Deprecate bind/start multi-process

---

docs/httpclient.rst
tornado/simple_httpclient.py

This method is not meant for public consumption; it is an
implementation detail of the construction-time magic for this class.
It was not intended to appear in documentation as if it is
the public constructor.
Fixes #3141

httpclient: Remove initialize method from docs

---

tornado/ioloop.py

asyncio is now unconditionally imported so these checks are redundant

remove unreachable asyncio checks

---

tornado/ioloop.py
tornado/platform/asyncio.py

so warnings are associated with the line where the deprecated methods are called rather than the line where the warning itself is
In:
```python
from tornado.ioloop import IOLoop
loop = IOLoop(make_current=False)
loop.make_current()
```
before:
```
tornado/platform/asyncio.py:341: DeprecationWarning: make_current is deprecated; start the event loop first
warnings.warn(
```
after:
```
test.py:4: DeprecationWarning: make_current is deprecated; start the event loop first
loop.make_current()
```

Add stacklevel to deprecation warnings

---

tornado/platform/asyncio.py
tornado/test/ioloop_test.py

allows patterns of creating and explicitly passing the asyncio loop before instantiating the IOLoop.
For example: creating a loop with the non-default event loop policy without having to set the current policy
This is actually related to #3156 where in some of our explicit background thread event loop setup, we've been creating the asyncio event loop prior to the tornado IOLoop. To avoid relying on the deprecated `asyncio.get_event_loop()`, we need to pass the asyncio loop directly to the tornado IOLoop.

Allow passing asyncio_loop argument to AsyncIOLoop

---

tornado/ioloop.py

The constructor is not completely deprecated; the make_current=False
mode is still usable.
Fixes #3156

ioloop: Update docs for IOLoop constructor

---

.github/workflows/build.yml
pyproject.toml
setup.py

This will produce cross-version wheels so we won't have to do
releases just to make new wheels when new versions of Python
are available.
Also modernize the build process a bit to require setuptools and use
the native "optional" flag for extensions.

setup: Build wheels with the stable ABI (abi3)

---

docs/releases/v6.2.0.rst

The change at the end is put in since I edited the doc in GitHub's browser. Feel free to remove if you don't want this.

Fix typo in release notes

---

tornado/iostream.py

According to the comment introduced in tornadoweb/tornado#1873,
bytearray shrink is done automatically in Python 3.4+.

Cleanup bytearray shrink code designed for Python 2

---

tornado/queues.py

A new error introduced to mypy is detected in tornado's repository. 
tornado (https://github.com/tornadoweb/tornado)
+ tornado/queues.py:384: error: A function returning TypeVar should receive at least one argument containing the same Typevar
+ tornado/queues.py:421: error: A function returning TypeVar should receive at least one argument containing the same Typevar
This PR adds ignore to that error.
Reference: https://github.com/python/mypy/pull/13166

add type-var ignore for the recently introduced mypy error

---

tornado/websocket.py

`SimpleAsyncHTTPClient` accepts a custom `resolver` instance, and this can be used to make an HTTP connection to Unix sockets (see also #2671). I would like to do the same with WebSocketClientConnection. It's possible by globally configuring the resolver class, but I'd prefer to do it without global side-effects.
For more context, this is part of an effort for jupyter-server-proxy to support proxying services listening securely on Unix sockets, as well as TCP sockets (https://github.com/jupyterhub/jupyter-server-proxy/pull/337 ). This is currently working apart from Websocket support, which this PR would make possible.

Allow custom resolver in WebSocketClientConnection

---

tornado/gen.py
tornado/test/gen_test.py

`Runner.handle_yield` uses `convert_yielded`, which uses `asyncio.ensure_future` for native coroutines. `asyncio.ensure_future` should be called with passed context.

Fix contextvars.Context propagation to first yield with native coroutines

---

tornado/auth.py

This slipped in with #3137 because that PR was submitted at a time when
the CI config was broken and I didn't notice the incomplete run.

auth: Fix lint error (long line)

---

tornado/websocket.py

I'm just opening this to start the discussion (originated from https://github.com/tornadoweb/tornado/issues/3007) on how we can improve the speed of websocket transfers. This small change reduced transferring a 206MB file from ~43 seconds to ~2 seconds.
`bytes` is immutable, so extending it with `+=` probably copies the entire buffer every time we have a new frame. I noticed that progress was also slower and slower, using the scripts here: https://github.com/tornadoweb/tornado/issues/3007
`bytearray` does not seem to suffer from this.
My only verification is by transferring the 206MB ZIP file, and verifying the md5sum of the two files are equal (and that the ZIP can be opened).

Changed websocket message buffer from bytes to bytearray

---

.github/workflows/test.yml
docs/index.rst
pyproject.toml
setup.cfg
setup.py
tox.ini

The main reason to drop this version before it reaches its EOL is so that we can begin to use unittest.IsolatedAsyncioTestCase to replace deprecated portions of the tornado.testing module.
A secondary reason is that Python 3.8 introduced support for the samesite cookie attribute, which allows us to deprecate the xsrf_token mechanism.

setup: Drop support for python 3.7

---

tornado/test/httpserver_test.py
tornado/test/testing_test.py
tornado/test/websocket_test.py
tornado/testing.py

ExpectLog is sensitive to the difference between tornado.testing.main (which sets the logging level to info) and most other test runners, which do not. In the future ExpectLog will match WARNING and above by default; matching lower levels without using the ``level`` argument is deprecated.
Fix one test in httpserver_test.py that is affected by this.

testing: Deprecate environment-dependent behavior in ExpectLog

---

README.rst
demos/blog/blog.py
demos/chat/chatdemo.py
demos/facebook/facebook.py
demos/file_upload/file_receiver.py
demos/helloworld/helloworld.py
demos/websocket/chatdemo.py
docs/auth.rst
docs/guide/security.rst
docs/guide/structure.rst
docs/guide/templates.rst
docs/index.rst
docs/websocket.rst
tornado/__init__.py
tornado/ioloop.py
tornado/iostream.py
tornado/options.py
tornado/test/escape_test.py
tornado/test/import_test.py
tornado/test/util_test.py
tornado/web.py
tornado/websocket.py

A getattr hook in the top-level "tornado" package now imports submodules automatically, eliminating the need to explicitly reference multiple submodules in imports

all: Support lazy imports of submodules

---

demos/blog/blog.py
demos/facebook/facebook.py
demos/twitter/twitterdemo.py
docs/guide/security.rst
docs/guide/templates.rst
docs/web.rst
tornado/auth.py
tornado/test/web_test.py
tornado/web.py

Various updates to cookie APIs
- Rename 'secure' to 'signed' in cookie methods
- clear_cookie accepts additional arguments
- clear_all_cookies is deprecated

web: Cookie updates

---

tornado/ioloop.py
tornado/platform/asyncio.py
tornado/tcpserver.py
tornado/test/asyncio_test.py
tornado/test/ioloop_test.py
tornado/test/testing_test.py
tornado/testing.py

This is an attempt to tackle #3216 - at least the straightforward parts of it.
- Remove deprecation warnings and notices for ioloop `make_current` and `clear_current` methods, and the `make_current` constructor parameter.
- Remove deprecation notices on `AsyncTestCase` and `AsyncHTTPTestCase`
- Remove the mention of Python changes from the TCPServer `bind` & `start` deprecation notices (but they're still deprecated)
I've assumed that removing the deprecation notices is sufficient documentation - we could add notes saying that they were deprecated and then undeprecated again, but that feels like unnecessary clutter.
Still to figure out:

Revert some deprecations, following asyncio changes

---

tornado/test/asyncio_test.py
tornado/testing.py

Also deprecate get_new_ioloop.

testing: No longer silence deprecation warnings

---

demos/README.rst
docs/guide/structure.rst
docs/httpclient.rst
docs/releases/v4.5.0.rst
tornado/web.py

Add a README to the demos directory with a brief description of each, and a warning about the usage of not-yet-released features.
Fixes #3236

docs: Point to stable branch for all demo links

---

docs/web.rst
tornado/test/web_test.py
tornado/web.py

This makes it possible to use the __Host- cookie prefix for increased
security

web: Support renaming the XSRF cookie

---

docs/releases/v6.3.0.rst
tornado/__init__.pyi
tornado/test/import_test.py
tornado/web.py
tornado/websocket.py

This makes the auto-import functionality compatible with mypy
and other typing-based tools such as autocomplete functionality.
Excluding these imports from static typing feels like a premature
optimization and made it much less appealing to make use of the
auto-imports.
This may slow down type checking of applications that use Tornado by
a little, since the type checker must now process all of Tornado and
not only the subset that was imported. However, the increasing use
of long-lived daemons for type checkers should mitigate this cost.

typing: Eagerly import all submodules in __init__.pyi

---

.github/workflows/build.yml
.github/workflows/test.yml
pyproject.toml

Build wheels for Python 3.12 as well.
Update various dependencies. The upload/download artifact actions
were using deprecated versions, and we were using a deprecated
macos build image. While we're at it, update the other OS versions
and cibuildwheel.

ci: Update build workflow

---

docs/releases.rst
docs/releases/v6.3.1.rst
tornado/test/web_test.py
tornado/web.py

This was an unintended feature that got broken in #3224. Bring it back for now but deprecate it for future cleanup.
Fixes #3252

web: Restore case-insensitivity of set_cookie args

---

.github/workflows/build.yml
tornado/test/websocket_test.py

These failures occur on the build.yml workflow on the emulated arm64
platform: an ill-timed timer firing during test shutdown can result
in a message being logged and the test failing for dirty logs.

test: Close a websocket client that causes occasional test failures

---

tornado/test/autoreload_test.py
tornado/test/log_test.py
tornado/test/runtests.py
tornado/test/web_test.py
tox.ini

- LANG tests were no longer having the intended effect because C locales now default to utf8 instead of ascii. There's a new warning we can turn on with an env var instead.
- The tox install_command issue was reverted in tox 1.9
- Python now guarantees that __file__ is absolute

test: Streamline test configurations

---

.github/workflows/build.yml

Replace the use of a special branch name for testing.

ci: Enable manual dispatch for build workflow

---

MANIFEST.in

Also remove the demos directory from sdist. This inclusion was incomplete and even if it were incomplete I don't think the sdist is a great way to distribute these demos.
Fixes #3253

setup: Include tox.ini in sdist

---

tornado/test/websocket_test.py
tornado/websocket.py

This gives a warning that is not dependent on GC for the issue in #3257.

websocket: Add warning if client connection isn't closed cleanly

---

tornado/web.py

Under some configurations the default_filename redirect could be exploited to redirect to an attacker-controlled site. This change refuses to redirect to URLs that could be misinterpreted.
A test case for the specific vulnerable configuration will follow after the patch has been available.

web: Fix an open redirect in StaticFileHandler

---

tornado/gen.py
tornado/ioloop.py

Per the warning in the asyncio documentation, we need to hold a strong reference to all asyncio Tasks to prevent premature GC. Following discussions in cpython (https://github.com/python/cpython/issues/91887), we hold these references on the IOLoop instance to ensure that they are strongly held but do not cause leaks if the event loop itself is discarded.
This is expected to fix all of the various "task was destroyed but it is pending" warnings that have been reported. The IOLoop._pending_tasks set is expected to become obsolete if corresponding changes are made to asyncio in Python 3.13.
Fixes #3209
Fixes #3047
Fixes #2763
Some issues involve this warning as their most visible symptom, but have an underlying cause that should still be addressed. Updates #2914
Updates #2356

gen: Hold strong references to all asyncio.Tasks

---

.github/workflows/test.yml

Current betas have a bug in GzipFile we can't easily work around. https://github.com/python/cpython/issues/105808

ci: Disable Python 3.12 in CI

---

tornado/platform/asyncio.py
tornado/test/asyncio_test.py

Attempt to clean up our selector thread (on windows) when the event loop shuts down without waiting for GC. We can't always do this, but we can at least detect it for asyncio.run. For cases where we do need to rely on GC, we now rely on the GC of the canary Task instead of the AddThreadSelectorEventLoop.
Fixes #3173

asyncio: Use a canary task to detect end of event loop

---

.github/workflows/test.yml
requirements.txt
tornado/httputil.py
tornado/locale.py
tornado/test/httpclient_test.py
tornado/test/httputil_test.py
tornado/test/locale_test.py
tornado/test/web_test.py
tornado/web.py

Now that the gzip bug (python/cpython#105808) is fixed in 3.12b3, we can bring that version back to CI. We also need to pick up a newer version of tox and make some changes to datetime handling to avoid deprecation warnings. 
Fixes #3278 
Closes #3277

Updates for Python 3.12

---

tornado/platform/asyncio.py

This hook was added because of an only-in-CI issue, but we have since improved our cleanup of the selector thread. As long as this passes CI, I think we can remove the atexit hook.
Fixes #3291

asyncio: Remove atexit hook

---

tornado/autoreload.py
tornado/test/autoreload_test.py

* Support running a directory instead of a module (#2855). In both the regular debug mode and CLI wrapper
* Use a real option parser for CLI wrapper
* Add `--until-success` flag (#2398)
* More tests!
* Remove some old compatibility code and update type annotations

autoreload: Various updates

---

tornado/test/web_test.py

Drive letters in windows absolute paths mess up this test, so remove them and use a path relative to the drive root instead.

web_test: Fix open redirect test on windows

---

tornado/test/httpserver_test.py

The github security advisory feature lets you make private PRs but it apparently doesn't support CI so this log failure wasn't caught until after the PR was merged.

httpserver_test: Add ExpectLog to fix CI

---

tornado/test/httpclient_test.py

This test has recently become flaky on windows CI, and before investigating further, see if it's just because the CI machines are overloaded and subprocesses are slower on windows.

httpclient_test: Increase test_destructor_log timeout

---

docs/conf.py

The old magic for sphinx_rtd_theme has been removed; now we should handle the theme in the same way we do for local builds.

docs: Fix build after readthedocs/readthedocs.org#10638

---

tornado/escape.py
tornado/test/escape_test.py

Many of these functions were necessary in Python 2, but are now
redundant. We can simply use the standard library in many cases.
The only major change is in xhtml_unescape, where we now reject
invalid character references such as surrogates and control characters.
Update docs throughout to be more specific about differences from the
standard library. Also be more complete about the ``plus`` option to
the url escaping functions.
Fixes #3186

escape: Use the standard library where possible

---

tornado/websocket.py

Hi,
This is my first time making PR to this repo. Wish this will help.
While developing libs based on Tornado, I found a mutable default argument value in `WebSocketClientConnection.__init__`.
```python
subprotocols: Optional[List[str]] = []
```
I think it's better to set the default argument value to `None` to prevent from some unpredictable problems.

Fix WebSocketClientConnection parameter

---

.github/workflows/test.yml

I've caused enough broken builds that aren't caught until the final release pipeline; time to add this to the main test config.

ci: Add windows to the main test config

---

tornado/platform/asyncio.py
tornado/test/circlerefs_test.py

This reverts commit https://github.com/tornadoweb/tornado/commit/62363740c1cc0e137ff4344c3afc3d52e070f200.
We are again seeing hangs at shutdown in
SyncHTTPClientTest.test_destructor_log. Maybe putting this back will
help.

Revert "asyncio: Remove atexit hook"

---

demos/blog/templates/feed.xml
demos/s3server/s3server.py
tornado/test/web_test.py
tornado/web.py

Add a simple test case to give us some basic coverage of this code path.
Closes #3335

web,demos: Remove more uses of deprecated datetime utc methods

---

tornado/iostream.py

Fix https://github.com/tornadoweb/tornado/issues/3355

OpenSSL 3.2 compatibility

---

tornado/test/testing_test.py
tornado/testing.py

Overriding _callTestMethod (which was introduced in python 3.8) is a less hacky way to detect tests that fail to use ``@gen_test`` where needed. It's not documented, but since Python 3.11 has introduced a similar check to the standard library we'll be able to remove it in the near future.
The major impetus for this change is an incompatibility with Pytest 8.2, which has made a change that tries to instantiate test classes at discovery time without an existing method name.
Fixes #3375
Closes #3374

testing: Replace _TestMethodWrapper with _callTestMethod

---

.github/workflows/build.yml
.github/workflows/test.yml

The changes to checkout and setup-python shouldn't have been major version bumps. upload-artifact and download-artifact should have had updated node versions on v3 so we don't have to adapt to incompatible changes here. But anyway, here we are.
build.yml has updates from
https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml

ci: Update action versions for node deprecation

---

tornado/curl_httpclient.py
tornado/http1connection.py
tornado/test/httpclient_test.py

libcurl does not check for CR and LF in headers, making this the application's responsibility. However, Tornado's other HTTP interfaces check for linefeeds so we should do the same here so that switching between the simple and curl http clients does not introduce header injection vulnerabilties.
http1connection previously checked only for LF in headers (alone or in a CRLF pair). It now prohibits bare CR as well, following the requirement in RFC 9112.

curl_httpclient,http1connection: Prohibit CR and LF in headers

---

tornado/http1connection.py
tornado/httputil.py
tornado/test/httpserver_test.py
tornado/test/httputil_test.py
tornado/test/simple_httpclient_test.py

Unexpected transfer-encoding values were previously ignored and treated
as the HTTP/1.0 default of read-until-close. This can lead to framing
issues with certain proxies. We now treat any unexpected value as an
error.
The RFC specifies that only tabs and spaces should be stripped.
Removing additonal whitespace characters can lead to framing
errors with certain proxies.

http1connection: Stricter handling of transfer-encoding and whitespace

---

tornado/curl_httpclient.py
tornado/httputil.py

Enhances typing for `RequestStartLine` and `ResponseStartLine`.
`HTTPServerRequest` may set its `method`/`uri`/`version` properties from `RequestStartLine`. On Pyright, since these properties' types are unknown, those `HTTPServerRequest` properties may also become unknown.

use typing.NamedTuple instead of collections.namedtuple

---

tornado/template.py

As per the docstring, `autoescape=None` can be passed to `BaseLoader`.

template: type BaseLoader autoescape kwarg as optional

---

tornado/web.py

Use the same overload technique as `get_argument()`.
Fixes https://github.com/tornadoweb/tornado/issues/3336

web: More accurate typing for get_{body,query}_argument()

---

requirements.txt
tornado/concurrent.py
tornado/httputil.py
tornado/platform/asyncio.py
tornado/test/concurrent_test.py
tornado/web.py
tornado/websocket.py

Picks up most of the open typing-related issues and PRs; see individual commits for details.
Fixes #3328
Fixes #3354 
Fixes #3050 
Fixes #3314

Update mypy and various typing improvements

---

.github/workflows/test.yml
setup.py
tornado/test/process_test.py
tornado/test/util_test.py
tornado/util.py
tox.ini

Belatedly promote 3.12 to non-beta status

Add python 3.13 betas to test configs

---

docs/releases/v3.0.0.rst
docs/releases/v3.2.0.rst
docs/releases/v5.0.0.rst
docs/twisted.rst
maint/scripts/test_resolvers.py
tornado/netutil.py
tornado/platform/twisted.py
tornado/test/netutil_test.py
tornado/test/tcpclient_test.py

This class was deprecated and slated for deletion in Tornado 7.0. However, it has become broken due to the adoption of RFC 8482 (which limits the use of the ANY query type in DNS) and it now fails for most domain names (with the exception of localhost). The upstream issue https://github.com/twisted/twisted/issues/10062 has been open for years which is a pretty good sign that no one is depending on this class and it's safe to remove it ahead of schedule.
This class was primarily intended to provide thread-free non-blocking DNS resolution. If that is still required,
`tornado.platform.caresresolver` is the next best option, although it has its own limitations which differ from TwistedResolver.

twisted: Delete TwistedResolver class

---

tornado/test/autoreload_test.py
tox.ini

I'm not sure exactly how these warnings are getting logged without causing the build to fail, but they are.

test: Address warnings about using the default encoding

---

requirements.txt
tornado/options.py
tornado/test/web_test.py

Use "is" instead of "==" for type comparisons.

lint: Update flake8 and friends

---

.readthedocs.yaml
docs/conf.py
docs/guide/async.rst
docs/guide/coroutines.rst
docs/guide/running.rst
docs/guide/security.rst
docs/guide/structure.rst
docs/guide/templates.rst
docs/testing.rst
requirements.in
requirements.txt
tornado/auth.py
tornado/gen.py
tornado/ioloop.py
tornado/iostream.py
tornado/testing.py
tornado/web.py
tornado/websocket.py
tox.ini

Remove pin to sphinx 5.x and remove sphinx-asyncio. Sphinx now supports
asyncio out of the box. Everything I've checked looks fine although I
haven't looked at every page.
Fixes https://github.com/tornadoweb/tornado/issues/3239

docs: Update sphinx (and the rest of the deps)

---

tornado/test/autoreload_test.py

This came up in the Debian package build of tornado, where we run the tests from a staged build of the module.

autoreload_test: Handle a relative PYTHONPATH

---

tornado/test/util_test.py

These two values should always match, but they're updated
manually so test to catch mistakes.
Closes https://github.com/tornadoweb/tornado/issues/3406
Also add a test to replace a long-skipped test for tornado.util.exec_in.

test: Verify that tornado.version and version_info match

---

tornado/netutil.py
tornado/test/httpserver_test.py

Linux offers an "abstract namespace" for Unix sockets, distinguished by the address comprising an initial null byte. Specifying a `file` argument describing an abstract namespace  address to `netutil.bind_unix_socket(…)` fails as a consequence of the additional, file-system orientated, processing performed: https://github.com/tornadoweb/tornado/blob/bdfc017c66817359158185561cee7878680cd841/tornado/netutil.py#L212-L222 The proposed changes avoid performing the file-system orientated processing for abstract namespace addresses.

Add support for binding Unix sockets in Linux's abstract namespace.

---

tornado/test/concurrent_test.py
tornado/test/httpserver_test.py
tornado/test/iostream_test.py
tornado/test/netutil_test.py
tornado/test/runtests.py
tornado/test/simple_httpclient_test.py
tornado/test/util.py
tornado/test/websocket_test.py

Adopt it everywhere we use this pattern and pull on some loose threads along the way. 
This change improves type-checking coverage and improves compatibility with alternative test runners such as pytest. However, it may increase the number of skipped tests reported in some environments.

Extract abstract base test logic from UnixSocketTest

---

tornado/test/web_test.py
tornado/web.py

Fixing https://github.com/tornadoweb/tornado/issues/3408

web: do not send 500 on invalid If-Modified-Since header

---

tornado/gen.py
tornado/iostream.py
tornado/netutil.py
tornado/options.py
tornado/tcpserver.py
tornado/test/__main__.py
tornado/test/gen_test.py
tornado/test/httpclient_test.py
tornado/test/httpserver_test.py
tornado/test/ioloop_test.py
tornado/test/iostream_test.py
tornado/test/netutil_test.py
tornado/test/options_test.py
tornado/test/simple_httpclient_test.py
tornado/test/tcpclient_test.py
tornado/test/util.py
tornado/test/web_test.py

We had some logic to skip tests along with other compatibility shims for old versions of python that can now be cleaned up.

test: Clean up code related to old versions of python

---

docs/conf.py

RTD will no longer do this automagically, so we need to add these lines explicitly for compatibility. See
https://about.readthedocs.com/blog/2024/07/addons-by-default/

docs: Add readthedocs configuration

---

.github/workflows/build.yml
setup.py

Our hacky override of the `bdist_wheel` command is no longer necessary and will stop working in future versions of setuptools. Remove it, and add tests with the `abi3audit` package to ensure that our official releases remain abi3-compatible. 
This PR replaces #3425 which fixed the future-setuptools compatibility but left the override in place.

setup: Simplify build of abi3 wheels and add tests

---

.github/workflows/build.yml
.github/workflows/test.yml

This mitigates a potential security risk identified by zizmor.

ci: Remove persist-credentials from our CI workflows

---

tornado/test/ioloop_test.py

This test uses implicit event loop creation but
avoided deprecation warnings because it ran in a
subprocess. Surprisingly, it is the only test we
have left for this pattern.

ioloop_test: Skip a test that no longer works on py3.14

---

tornado/test/httputil_test.py

Simple typo fix in test variable name.
Before: requets
After:  request

Fix typo in test variable name (requets -> request)

---

tornado/httpserver.py
tornado/tcpserver.py

I noticed this code snippet will always fail:
```python
await asyncio.Event.wait()
```
because `wait` is an instance method. The correct incantation exists in other parts of the documentation, so this is probably just a little typo.

Fix a docstring typo for the usage of asyncio.Event.wait

---

docs/releases.rst
docs/releases/v6.4.2.rst
tornado/__init__.py
tornado/httputil.py
tornado/test/httputil_test.py
tornado/test/twisted_test.py

Maliciously-crafted cookies can cause Tornado to
spend an unreasonable amount of CPU time and block
the event loop.
This change replaces the quadratic algorithm with
a more efficient one. The implementation is copied
from the Python 3.13 standard library (the
previous one was from Python 3.5).
Fixes CVE-2024-52804
See CVE-2024-7592 for a similar vulnerability in cpython.
Thanks to @kexinoh for the report.

httputil: Fix quadratic performance of cookie parsing

---

pyproject.toml

Simple change to cross-compile a windows arm64 wheel. (#3456)
While this cannot be tested in the CI until GitHub starts supporting [Windows arm64 machines for open source projects](https://github.com/orgs/community/discussions/148648#discussioncomment-11920058), I did test the wheel this produced locally on an arm64 Windows machine and it passed all tests.

Add windows arm64 build

---

.github/workflows/build.yml
.github/workflows/test.yml
pyproject.toml

This speeds up the build job dramatically by eliminating the need for
emulation.
MacOS builds have also shifted to run on arm hosts instead of x86 hosts,
and it's now possible to run tests for both arm and x86 on the same
host.
New timings:
- macOS: 9:00
- ubuntu (intel): 10:15
- ubuntu (arm): 6:55
- windows: 14:50
Previously, the ubuntu build (for intel + emulated arm) took 22 minutes, so we've subtracted 7 minutes from the job run time (windows is now the long pole) and 5 minutes of total running time. Note that we're expanding the test coverage by running the full test suite on arm now, so an apples-to-apples comparison would show even more time savings.

ci: Use native arm builders

---

tornado/httputil.py
tornado/test/httputil_test.py

Previously we allowed nearly any string in header names, but RFC 9110 restricts them to certain printable ASCII characters.
Fixes #3310
Fixes #2790

httputil: Enforce RFC rules for header names

---

tornado/test/web_test.py
tornado/web.py

Addresses https://github.com/tornadoweb/tornado/issues/3450

Allow horizontal tabs in header values

---

tornado/test/web_test.py

A PR that failed lint (#3451) was merged because CI somehow didn't run on it.

web_test: Fix the build

---

tornado/httputil.py
tornado/test/httpserver_test.py

The method is now restricted to being valid token characters as defined
in RFC 9110, allowing us to correctly issue status code 400 or 405
as appropriate (this can make a difference with some caching proxies).
The request-target no longer allows control characters. This is less
strict than the RFC (which does not allow non-ascii characters),
but prioritizes backwards compatibility.
Fixes https://github.com/tornadoweb/tornado/issues/3415
Closes https://github.com/tornadoweb/tornado/pull/3338

httputil: Make parse_request_start_line stricter

---

tornado/ioloop.py
tornado/test/ioloop_test.py

keeps TimeoutError for maximum compatibility in case any existing code is handling this case (I just wrote some, but may not keep it), but e.g. RuntimeError or other might be most appropriate.
closes #3435

improve error message when run_sync does not complete for reasons other than timeout

---

tornado/web.py

Attempts to fix the [jupyter_server/issues/1503](https://github.com/jupyter-server/jupyter_server/issues/1503) issue
For details please see the linked issue. TLDR is that if the `log_message` contents have the literal '%' those are getting converted to '%%' when no formatting args are specified. When `HTTPError.__str__` is called, log_message is always %-formatted even when no formatting args are specified, and the '%' literal replacement is likely to avoid issues here.
This pr performs %-formatting of log_message only when required (args are specified) to avoid having to do the literal replacement.
While not completely a parallel example this is more or less what python's logging module does when creating a string out of a LogRecord: …

Format HTTPError.log_message only if args provided

---

tornado/test/websocket_test.py
tornado/websocket.py

Closes #3258
Closes #2905
Closes #2655
Fixes an issue with the calculation of ping timeout interval which caused connections to be erroneously closed from the server end. This could happen shortly after the connection was opened, *before* the ping was even sent (as reported in #3258) as the result of startup logic. It could also happen when pong responses were sent back from the client *within* the configured timeout as the result of a race condition.
To test this fix, try repeating the steps in this example: https://github.com/tornadoweb/tornado/issues/3258#issuecomment-2084940884
~I found a [TODO](https://github.com/tornadoweb/tornado/blob/f399f40fde0ae1b130646db783a6f79cc59231b2/tornado/test/websocket_test.py#L817) to implement testing for ping timeout. I tried to fill this in but …

websockets: fix ping_timeout

---

.github/zizmor.yml

This restores behavior of version 1.5.2 to be more lenient for pypa and astral-sh repos.

ci: Add zizmor config file

---

tornado/websocket.py

- Mention units for ping settings (#2655)
- Remove obsolete reference to 30s default timeout
- Link to a more recent version of python docs

websocket: Small doc updates

---

tornado/httputil.py
tornado/test/httpclient_test.py

HTTPHeaders had undocumented assumptions about trailing whitespace, leading to an unintentional regression in Tornado 6.4.1 in which passing the arguments of an AsyncHTTPClient header_callback to HTTPHeaders.parse_line would result in errors.
This commit moves newline parsing from parse to parse_line. It also strips trailing whitespace from continuation lines (trailing whitespace is not allowed in HTTP headers, but we didn't reject it in continuation lines).
This commit also deprecates continuation lines and the legacy handling of LF without CR.
Fixes #3321

httputil: Improve handling of trailing whitespace in headers

---

tornado/test/websocket_test.py
tornado/websocket.py

This was missed in the 6.0-era deprecation of callback arguments. The on_message_callback remains because even in coroutine-oriented code it is often more convenient to use a callback than to loop on read_message.

websocket: deprecate callback argument to websocket_connect

---

tornado/httputil.py
tornado/test/httpserver_test.py
tornado/test/web_test.py

- It is now an error to have multiple Host headers
- The Host header is now mandatory except in HTTP/1.0 mode
- Host headers containing characters that are disallowed by RFC 3986 are now rejected
Fixes #3468

httputil: Process the Host header more strictly

---

tornado/httputil.py
tornado/test/httputil_test.py

The obs-fold feature is defined only for tabs and spaces. The str.isspace() method also accepts other whitespace characters. These characters are not valid in HTTP headers and should be treated as errors instead of triggering line folding.
Fixes #3480

httputil: Reject header lines beginning with invalid whitespace

---

tornado/httputil.py
tornado/test/httputil_test.py

NUL, CR, and other control characters are not allowed in HTTP header values.
Fixes #3481

httputil: Forbid control chars and CR in header values

---

tornado/web.py

Document the fact that sometimes prepare() is not called, even if initialize() and on_finish() are.
Updates #3430
Closes #3431

web: Update docstrings for prepare and on_finish

---

tornado/gen.py

This diff resolves https://github.com/tornadoweb/tornado/issues/3142 .
Minimal repro:
```python
from tornado import gen
async def foo() -> int:
return 1
async def bar() -> str:
return "hello"
awaitables = [foo(), bar()]
gen.multi(awaitables)
```
Before patch:
```
🚂  mypy repro.py
/Users/jrheard/dev/tornado/tornado/tcpclient.py:274: error: Argument 1 to "_create_stream" of "TCPClient" has incompatible type "int | None"; expected "int"  [arg-type]
/Users/jrheard/dev/tornado/tornado/curl_httpclient.py:366: error: Argument 2 to "_curl_header_callback" of "CurlAsyncHTTPClient" has incompatible type "Callable[[str], None] | None"; expected "Callable[[str], None]"  [arg-type]
repro.py:14: error: Argument 1 to "multi" has incompatible type "list[Coroutine[Any, Any, object]]"; expected …
```

#3142: Improve usability of multi() and multi_future() type annotations

---

setup.py
tornado/speedups.c

- Defining the `Py_LIMITED_API` macro leads to build failures
- Do not re-enable GIL when importing `tornado.speedups` since it's thread-safe.

Don't define Py_LIMITED_API and don't re-enable GIL under free-threading

---

.github/workflows/test.yml
requirements.txt
tornado/testing.py

The deprecation warning for this function was reverted for 3.14b1.
See https://github.com/python/cpython/issues/130322

testing: Remove deprecation warning filter for set_event_loop

---

tornado/platform/asyncio.py
tornado/test/asyncio_test.py

windows
```python
import tornado.ioloop
import tornado.web
import contextvars
v = contextvars.ContextVar('v', default='default')
class MainHandler(tornado.web.RequestHandler):
def get(self):
print(v.get())
self.write("Hello, World!")
def make_app():
return tornado.web.Application([
(r"/", MainHandler),
])
if __name__ == "__main__":
v.set('foo')
app = make_app()
app.listen(8888)  # Listen on port 8888
print("Server is running on http://localhost:8888")
tornado.ioloop.IOLoop.current().start()
```
Run and visit http://localhost:8888, then print default

Fixed the bug that the handler cannot get the main thread context on the Windows platform.

---

tornado/httputil.py
tornado/test/httpserver_test.py
tornado/test/httputil_test.py
tornado/web.py

We used to continue after logging an error, which allowed repeated errors to spam the logs. The error raised here will still be logged, but only once per request, consistent with other error handling in Tornado.

httputil: Raise errors instead of logging in multipart/form-data parsing

---

docs/releases.rst
docs/releases/v6.5.1.rst
tornado/__init__.py
tornado/httputil.py
tornado/test/httputil_test.py

The change to be stricter about characters allowed in HTTP headers inadvertently broke support for non-latin1 filenames in multipart uploads (this was missed in testing because our i18n test case only used characters in latin1). This commit adds a hacky workaround without changing any APIs to make it safe for a 6.5.1 patch release; a more robust solution will follow for future releases.
Fixes #3502

httputil: Fix support for non-latin1 filenames in multipart uploads

---

.github/workflows/build.yml
pyproject.toml

Now that native ARM builders are available for windows, we can use them instead of cross-compiling. This improves parallelism in our build and speeds things up a bit, plus we can test the windows-arm builds now.
Also stop producing x86_64 builds for macos, since they are redundant with the universal2 builds (the x86_64 builds were useful with older version of pip, but they've been fully supported for 5 years now).

ci: Use Windows ARM builders

---

tornado/httputil.py

This argument was mistakenly removed in Tornado 6.5.0 with no warning; it is now back but deprecated. The host header should be used instead.
Updates #3468

httputil: Restore the host argument to HTTPServerRequest

---

tornado/http1connection.py
tornado/routing.py
tornado/test/httpclient_test.py
tornado/test/httpserver_test.py

This was previously being logged as an uncaught exception in application code, which is wrong for a malformed request. HTTPInputError now passes through the app-error logging to be caught and reported as a 400 (which logs at the warning level to the access log and info to the general log).
Fixes #3510

http1connection: Improve error logging for invalid host headers

---

docs/web.rst
tornado/test/websocket_test.py
tornado/websocket.py

* Fix a bug that caused the ping interval to be less frequent than configured.
* Fix erroneous documentation of the websocket_ping_timeout default and clarify units for the ping interval.

websocket_ping: fix ping interval with non-zero timeout and improve docs

---

tornado/test/web_test.py

When warnings are in context-aware mode (the default in free-threaded Python 3.14), the server captures the context from setUp and does not see the warning filter installed in the test method. Move the warning filter into the handler so it works consistently regardless of the context_aware_warnings flag.
Updates #3501

web_test: Move an ignore_deprecation block

---

docs/releases/v6.5.2.rst

docs: Fix a broken link in release notes
